// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `autonews.jce'
// **********************************************************************

package com.duowan.autonews;

public final class CarDetailItemDetail extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "autonews.CarDetailItemDetail";
    }

    public String fullClassName()
    {
        return "com.duowan.autonews.CarDetailItemDetail";
    }

    public int itemId = 0;

    public String name = "";

    public String price = "";

    public java.util.ArrayList<com.duowan.autonews.ItemDetail> detail = null;

    public int getItemId()
    {
        return itemId;
    }

    public void  setItemId(int itemId)
    {
        this.itemId = itemId;
    }

    public String getName()
    {
        return name;
    }

    public void  setName(String name)
    {
        this.name = name;
    }

    public String getPrice()
    {
        return price;
    }

    public void  setPrice(String price)
    {
        this.price = price;
    }

    public java.util.ArrayList<com.duowan.autonews.ItemDetail> getDetail()
    {
        return detail;
    }

    public void  setDetail(java.util.ArrayList<com.duowan.autonews.ItemDetail> detail)
    {
        this.detail = detail;
    }

    public CarDetailItemDetail()
    {
        setItemId(itemId);
        setName(name);
        setPrice(price);
        setDetail(detail);
    }

    public CarDetailItemDetail(int itemId, String name, String price, java.util.ArrayList<com.duowan.autonews.ItemDetail> detail)
    {
        setItemId(itemId);
        setName(name);
        setPrice(price);
        setDetail(detail);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        CarDetailItemDetail t = (CarDetailItemDetail) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(itemId, t.itemId) && 
            com.duowan.taf.jce.JceUtil.equals(name, t.name) && 
            com.duowan.taf.jce.JceUtil.equals(price, t.price) && 
            com.duowan.taf.jce.JceUtil.equals(detail, t.detail) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(itemId, 0);
        if (null != name)
        {
            _os.write(name, 1);
        }
        if (null != price)
        {
            _os.write(price, 2);
        }
        if (null != detail)
        {
            _os.write(detail, 3);
        }
    }

    static java.util.ArrayList<com.duowan.autonews.ItemDetail> cache_detail;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setItemId((int) _is.read(itemId, 0, false));

        setName( _is.readString(1, false));

        setPrice( _is.readString(2, false));

        if(null == cache_detail)
        {
            cache_detail = new java.util.ArrayList<com.duowan.autonews.ItemDetail>();
            com.duowan.autonews.ItemDetail __var_8 = new com.duowan.autonews.ItemDetail();
            ((java.util.ArrayList<com.duowan.autonews.ItemDetail>)cache_detail).add(__var_8);
        }
        setDetail((java.util.ArrayList<com.duowan.autonews.ItemDetail>) _is.read(cache_detail, 3, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(itemId, "itemId");
        _ds.display(name, "name");
        _ds.display(price, "price");
        _ds.display(detail, "detail");
    }

}

