// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `autonews.jce'
// **********************************************************************

package com.duowan.autonews;

public final class CarImageList extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "autonews.CarImageList";
    }

    public String fullClassName()
    {
        return "com.duowan.autonews.CarImageList";
    }

    public String title = "";

    public java.util.ArrayList<com.duowan.autonews.CarPicInfo> picList = null;

    public String getTitle()
    {
        return title;
    }

    public void  setTitle(String title)
    {
        this.title = title;
    }

    public java.util.ArrayList<com.duowan.autonews.CarPicInfo> getPicList()
    {
        return picList;
    }

    public void  setPicList(java.util.ArrayList<com.duowan.autonews.CarPicInfo> picList)
    {
        this.picList = picList;
    }

    public CarImageList()
    {
        setTitle(title);
        setPicList(picList);
    }

    public CarImageList(String title, java.util.ArrayList<com.duowan.autonews.CarPicInfo> picList)
    {
        setTitle(title);
        setPicList(picList);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        CarImageList t = (CarImageList) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(title, t.title) && 
            com.duowan.taf.jce.JceUtil.equals(picList, t.picList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != title)
        {
            _os.write(title, 0);
        }
        if (null != picList)
        {
            _os.write(picList, 1);
        }
    }

    static java.util.ArrayList<com.duowan.autonews.CarPicInfo> cache_picList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setTitle( _is.readString(0, false));

        if(null == cache_picList)
        {
            cache_picList = new java.util.ArrayList<com.duowan.autonews.CarPicInfo>();
            com.duowan.autonews.CarPicInfo __var_10 = new com.duowan.autonews.CarPicInfo();
            ((java.util.ArrayList<com.duowan.autonews.CarPicInfo>)cache_picList).add(__var_10);
        }
        setPicList((java.util.ArrayList<com.duowan.autonews.CarPicInfo>) _is.read(cache_picList, 1, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(title, "title");
        _ds.display(picList, "picList");
    }

}

