// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `autonews.jce'
// **********************************************************************

package com.duowan.autonews;

public final class CarPicInfo extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "autonews.CarPicInfo";
    }

    public String fullClassName()
    {
        return "com.duowan.autonews.CarPicInfo";
    }

    public int width = 0;

    public int height = 0;

    public String smallUrl = "";

    public String bigUrl = "";

    public String desc = "";

    public int getWidth()
    {
        return width;
    }

    public void  setWidth(int width)
    {
        this.width = width;
    }

    public int getHeight()
    {
        return height;
    }

    public void  setHeight(int height)
    {
        this.height = height;
    }

    public String getSmallUrl()
    {
        return smallUrl;
    }

    public void  setSmallUrl(String smallUrl)
    {
        this.smallUrl = smallUrl;
    }

    public String getBigUrl()
    {
        return bigUrl;
    }

    public void  setBigUrl(String bigUrl)
    {
        this.bigUrl = bigUrl;
    }

    public String getDesc()
    {
        return desc;
    }

    public void  setDesc(String desc)
    {
        this.desc = desc;
    }

    public CarPicInfo()
    {
        setWidth(width);
        setHeight(height);
        setSmallUrl(smallUrl);
        setBigUrl(bigUrl);
        setDesc(desc);
    }

    public CarPicInfo(int width, int height, String smallUrl, String bigUrl, String desc)
    {
        setWidth(width);
        setHeight(height);
        setSmallUrl(smallUrl);
        setBigUrl(bigUrl);
        setDesc(desc);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        CarPicInfo t = (CarPicInfo) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(width, t.width) && 
            com.duowan.taf.jce.JceUtil.equals(height, t.height) && 
            com.duowan.taf.jce.JceUtil.equals(smallUrl, t.smallUrl) && 
            com.duowan.taf.jce.JceUtil.equals(bigUrl, t.bigUrl) && 
            com.duowan.taf.jce.JceUtil.equals(desc, t.desc) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(width, 0);
        _os.write(height, 1);
        if (null != smallUrl)
        {
            _os.write(smallUrl, 2);
        }
        if (null != bigUrl)
        {
            _os.write(bigUrl, 3);
        }
        if (null != desc)
        {
            _os.write(desc, 4);
        }
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setWidth((int) _is.read(width, 0, false));

        setHeight((int) _is.read(height, 1, false));

        setSmallUrl( _is.readString(2, false));

        setBigUrl( _is.readString(3, false));

        setDesc( _is.readString(4, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(width, "width");
        _ds.display(height, "height");
        _ds.display(smallUrl, "smallUrl");
        _ds.display(bigUrl, "bigUrl");
        _ds.display(desc, "desc");
    }

}

