// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `autonews.jce'
// **********************************************************************

package com.duowan.autonews;

public final class GetCarListReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "autonews.GetCarListReq";
    }

    public String fullClassName()
    {
        return "com.duowan.autonews.GetCarListReq";
    }

    public int count = 0;

    public String attachInfo = "";

    public int brandId = 0;

    public int getCount()
    {
        return count;
    }

    public void  setCount(int count)
    {
        this.count = count;
    }

    public String getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public int getBrandId()
    {
        return brandId;
    }

    public void  setBrandId(int brandId)
    {
        this.brandId = brandId;
    }

    public GetCarListReq()
    {
        setCount(count);
        setAttachInfo(attachInfo);
        setBrandId(brandId);
    }

    public GetCarListReq(int count, String attachInfo, int brandId)
    {
        setCount(count);
        setAttachInfo(attachInfo);
        setBrandId(brandId);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetCarListReq t = (GetCarListReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(count, t.count) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) && 
            com.duowan.taf.jce.JceUtil.equals(brandId, t.brandId) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(count, 0);
        if (null != attachInfo)
        {
            _os.write(attachInfo, 1);
        }
        _os.write(brandId, 2);
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setCount((int) _is.read(count, 0, false));

        setAttachInfo( _is.readString(1, false));

        setBrandId((int) _is.read(brandId, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(count, "count");
        _ds.display(attachInfo, "attachInfo");
        _ds.display(brandId, "brandId");
    }

}

