// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `autonews.jce'
// **********************************************************************

package com.duowan.autonews;

public final class GetCarBrandListRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "autonews.GetCarBrandListRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.autonews.GetCarBrandListRsp";
    }

    public java.util.Map<String, java.util.ArrayList<com.duowan.autonews.CarBrandInfo>> allBrandInfo = null;

    public java.util.Map<String, java.util.ArrayList<com.duowan.autonews.CarBrandInfo>> getAllBrandInfo()
    {
        return allBrandInfo;
    }

    public void  setAllBrandInfo(java.util.Map<String, java.util.ArrayList<com.duowan.autonews.CarBrandInfo>> allBrandInfo)
    {
        this.allBrandInfo = allBrandInfo;
    }

    public GetCarBrandListRsp()
    {
        setAllBrandInfo(allBrandInfo);
    }

    public GetCarBrandListRsp(java.util.Map<String, java.util.ArrayList<com.duowan.autonews.CarBrandInfo>> allBrandInfo)
    {
        setAllBrandInfo(allBrandInfo);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetCarBrandListRsp t = (GetCarBrandListRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(allBrandInfo, t.allBrandInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != allBrandInfo)
        {
            _os.write(allBrandInfo, 0);
        }
    }

    static java.util.Map<String, java.util.ArrayList<com.duowan.autonews.CarBrandInfo>> cache_allBrandInfo;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_allBrandInfo)
        {
            cache_allBrandInfo = new java.util.HashMap<String, java.util.ArrayList<com.duowan.autonews.CarBrandInfo>>();
            String __var_1 = "";
            java.util.ArrayList<com.duowan.autonews.CarBrandInfo> __var_2 = new java.util.ArrayList<com.duowan.autonews.CarBrandInfo>();
            com.duowan.autonews.CarBrandInfo __var_3 = new com.duowan.autonews.CarBrandInfo();
            ((java.util.ArrayList<com.duowan.autonews.CarBrandInfo>)__var_2).add(__var_3);
            cache_allBrandInfo.put(__var_1, __var_2);
        }
        setAllBrandInfo((java.util.Map<String, java.util.ArrayList<com.duowan.autonews.CarBrandInfo>>) _is.read(cache_allBrandInfo, 0, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(allBrandInfo, "allBrandInfo");
    }

}

