// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `autonews.jce'
// **********************************************************************

package com.duowan.autonews;

public final class GetCarDetailRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "autonews.GetCarDetailRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.autonews.GetCarDetailRsp";
    }

    public com.duowan.autonews.CarDetail detail = null;

    public int hasMore = 0;

    public String attachInfo = "";

    public com.duowan.autonews.CarDetail getDetail()
    {
        return detail;
    }

    public void  setDetail(com.duowan.autonews.CarDetail detail)
    {
        this.detail = detail;
    }

    public int getHasMore()
    {
        return hasMore;
    }

    public void  setHasMore(int hasMore)
    {
        this.hasMore = hasMore;
    }

    public String getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public GetCarDetailRsp()
    {
        setDetail(detail);
        setHasMore(hasMore);
        setAttachInfo(attachInfo);
    }

    public GetCarDetailRsp(com.duowan.autonews.CarDetail detail, int hasMore, String attachInfo)
    {
        setDetail(detail);
        setHasMore(hasMore);
        setAttachInfo(attachInfo);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetCarDetailRsp t = (GetCarDetailRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(detail, t.detail) && 
            com.duowan.taf.jce.JceUtil.equals(hasMore, t.hasMore) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != detail)
        {
            _os.write(detail, 0);
        }
        _os.write(hasMore, 1);
        if (null != attachInfo)
        {
            _os.write(attachInfo, 2);
        }
    }

    static com.duowan.autonews.CarDetail cache_detail;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_detail)
        {
            cache_detail = new com.duowan.autonews.CarDetail();
        }
        setDetail((com.duowan.autonews.CarDetail) _is.read(cache_detail, 0, false));

        setHasMore((int) _is.read(hasMore, 1, false));

        setAttachInfo( _is.readString(2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(detail, "detail");
        _ds.display(hasMore, "hasMore");
        _ds.display(attachInfo, "attachInfo");
    }

}

