// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `autonews.jce'
// **********************************************************************

package com.duowan.autonews;

public final class GetHotCarListRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "autonews.GetHotCarListRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.autonews.GetHotCarListRsp";
    }

    public int hasMore = 0;

    public String attachInfo = "";

    public java.util.ArrayList<com.duowan.autonews.CarListInfo> hotCarList = null;

    public int getHasMore()
    {
        return hasMore;
    }

    public void  setHasMore(int hasMore)
    {
        this.hasMore = hasMore;
    }

    public String getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public java.util.ArrayList<com.duowan.autonews.CarListInfo> getHotCarList()
    {
        return hotCarList;
    }

    public void  setHotCarList(java.util.ArrayList<com.duowan.autonews.CarListInfo> hotCarList)
    {
        this.hotCarList = hotCarList;
    }

    public GetHotCarListRsp()
    {
        setHasMore(hasMore);
        setAttachInfo(attachInfo);
        setHotCarList(hotCarList);
    }

    public GetHotCarListRsp(int hasMore, String attachInfo, java.util.ArrayList<com.duowan.autonews.CarListInfo> hotCarList)
    {
        setHasMore(hasMore);
        setAttachInfo(attachInfo);
        setHotCarList(hotCarList);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetHotCarListRsp t = (GetHotCarListRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(hasMore, t.hasMore) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) && 
            com.duowan.taf.jce.JceUtil.equals(hotCarList, t.hotCarList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(hasMore, 0);
        if (null != attachInfo)
        {
            _os.write(attachInfo, 1);
        }
        if (null != hotCarList)
        {
            _os.write(hotCarList, 2);
        }
    }

    static java.util.ArrayList<com.duowan.autonews.CarListInfo> cache_hotCarList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setHasMore((int) _is.read(hasMore, 0, false));

        setAttachInfo( _is.readString(1, false));

        if(null == cache_hotCarList)
        {
            cache_hotCarList = new java.util.ArrayList<com.duowan.autonews.CarListInfo>();
            com.duowan.autonews.CarListInfo __var_4 = new com.duowan.autonews.CarListInfo();
            ((java.util.ArrayList<com.duowan.autonews.CarListInfo>)cache_hotCarList).add(__var_4);
        }
        setHotCarList((java.util.ArrayList<com.duowan.autonews.CarListInfo>) _is.read(cache_hotCarList, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(hasMore, "hasMore");
        _ds.display(attachInfo, "attachInfo");
        _ds.display(hotCarList, "hotCarList");
    }

}

