// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `autonews.jce'
// **********************************************************************

package com.duowan.autonews;

public final class ItemDetail extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "autonews.ItemDetail";
    }

    public String fullClassName()
    {
        return "com.duowan.autonews.ItemDetail";
    }

    public String name = "";

    public java.util.ArrayList<com.duowan.autonews.SubItemDetail> subList = null;

    public String getName()
    {
        return name;
    }

    public void  setName(String name)
    {
        this.name = name;
    }

    public java.util.ArrayList<com.duowan.autonews.SubItemDetail> getSubList()
    {
        return subList;
    }

    public void  setSubList(java.util.ArrayList<com.duowan.autonews.SubItemDetail> subList)
    {
        this.subList = subList;
    }

    public ItemDetail()
    {
        setName(name);
        setSubList(subList);
    }

    public ItemDetail(String name, java.util.ArrayList<com.duowan.autonews.SubItemDetail> subList)
    {
        setName(name);
        setSubList(subList);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ItemDetail t = (ItemDetail) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(name, t.name) && 
            com.duowan.taf.jce.JceUtil.equals(subList, t.subList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != name)
        {
            _os.write(name, 0);
        }
        if (null != subList)
        {
            _os.write(subList, 1);
        }
    }

    static java.util.ArrayList<com.duowan.autonews.SubItemDetail> cache_subList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setName( _is.readString(0, false));

        if(null == cache_subList)
        {
            cache_subList = new java.util.ArrayList<com.duowan.autonews.SubItemDetail>();
            com.duowan.autonews.SubItemDetail __var_7 = new com.duowan.autonews.SubItemDetail();
            ((java.util.ArrayList<com.duowan.autonews.SubItemDetail>)cache_subList).add(__var_7);
        }
        setSubList((java.util.ArrayList<com.duowan.autonews.SubItemDetail>) _is.read(cache_subList, 1, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(name, "name");
        _ds.display(subList, "subList");
    }

}

