// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `CommBase.jce'
// **********************************************************************

package com.duowan.Comm;

public final class CommStat extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "Comm.CommStat";
    }

    public String fullClassName()
    {
        return "com.duowan.Comm.CommStat";
    }

    public com.duowan.Comm.CommUserbase tUB = null;

    public String sProtocol = "";

    public com.duowan.Comm.CommUserbase getTUB()
    {
        return tUB;
    }

    public void  setTUB(com.duowan.Comm.CommUserbase tUB)
    {
        this.tUB = tUB;
    }

    public String getSProtocol()
    {
        return sProtocol;
    }

    public void  setSProtocol(String sProtocol)
    {
        this.sProtocol = sProtocol;
    }

    public CommStat()
    {
        setTUB(tUB);
        setSProtocol(sProtocol);
    }

    public CommStat(com.duowan.Comm.CommUserbase tUB, String sProtocol)
    {
        setTUB(tUB);
        setSProtocol(sProtocol);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        CommStat t = (CommStat) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(tUB, t.tUB) && 
            com.duowan.taf.jce.JceUtil.equals(sProtocol, t.sProtocol) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(tUB, 0);
        if (null != sProtocol)
        {
            _os.write(sProtocol, 1);
        }
    }

    static com.duowan.Comm.CommUserbase cache_tUB;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_tUB)
        {
            cache_tUB = new com.duowan.Comm.CommUserbase();
        }
        setTUB((com.duowan.Comm.CommUserbase) _is.read(cache_tUB, 0, true));

        setSProtocol( _is.readString(1, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(tUB, "tUB");
        _ds.display(sProtocol, "sProtocol");
    }

}

