// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `CommBase.jce'
// **********************************************************************

package com.duowan.Comm;

public final class CommUserbase extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "Comm.CommUserbase";
    }

    public String fullClassName()
    {
        return "com.duowan.Comm.CommUserbase";
    }

    public int eType = 0;

    public byte [] vGuid = null;

    public com.duowan.Comm.AppUA tUA = null;

    public String sIMEI = "";

    public long yyuid = 0;

    public String sAPN = "";

    public String sNetType = "";

    public int getEType()
    {
        return eType;
    }

    public void  setEType(int eType)
    {
        this.eType = eType;
    }

    public byte [] getVGuid()
    {
        return vGuid;
    }

    public void  setVGuid(byte [] vGuid)
    {
        this.vGuid = vGuid;
    }

    public com.duowan.Comm.AppUA getTUA()
    {
        return tUA;
    }

    public void  setTUA(com.duowan.Comm.AppUA tUA)
    {
        this.tUA = tUA;
    }

    public String getSIMEI()
    {
        return sIMEI;
    }

    public void  setSIMEI(String sIMEI)
    {
        this.sIMEI = sIMEI;
    }

    public long getYyuid()
    {
        return yyuid;
    }

    public void  setYyuid(long yyuid)
    {
        this.yyuid = yyuid;
    }

    public String getSAPN()
    {
        return sAPN;
    }

    public void  setSAPN(String sAPN)
    {
        this.sAPN = sAPN;
    }

    public String getSNetType()
    {
        return sNetType;
    }

    public void  setSNetType(String sNetType)
    {
        this.sNetType = sNetType;
    }

    public CommUserbase()
    {
        setEType(eType);
        setVGuid(vGuid);
        setTUA(tUA);
        setSIMEI(sIMEI);
        setYyuid(yyuid);
        setSAPN(sAPN);
        setSNetType(sNetType);
    }

    public CommUserbase(int eType, byte [] vGuid, com.duowan.Comm.AppUA tUA, String sIMEI, long yyuid, String sAPN, String sNetType)
    {
        setEType(eType);
        setVGuid(vGuid);
        setTUA(tUA);
        setSIMEI(sIMEI);
        setYyuid(yyuid);
        setSAPN(sAPN);
        setSNetType(sNetType);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        CommUserbase t = (CommUserbase) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(eType, t.eType) && 
            com.duowan.taf.jce.JceUtil.equals(vGuid, t.vGuid) && 
            com.duowan.taf.jce.JceUtil.equals(tUA, t.tUA) && 
            com.duowan.taf.jce.JceUtil.equals(sIMEI, t.sIMEI) && 
            com.duowan.taf.jce.JceUtil.equals(yyuid, t.yyuid) && 
            com.duowan.taf.jce.JceUtil.equals(sAPN, t.sAPN) && 
            com.duowan.taf.jce.JceUtil.equals(sNetType, t.sNetType) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(eType, 0);
        if (null != vGuid)
        {
            _os.write(vGuid, 1);
        }
        if (null != tUA)
        {
            _os.write(tUA, 2);
        }
        if (null != sIMEI)
        {
            _os.write(sIMEI, 3);
        }
        _os.write(yyuid, 4);
        if (null != sAPN)
        {
            _os.write(sAPN, 5);
        }
        if (null != sNetType)
        {
            _os.write(sNetType, 6);
        }
    }

    static int cache_eType;
    static byte [] cache_vGuid;
    static com.duowan.Comm.AppUA cache_tUA;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setEType((int) _is.read(eType, 0, false));

        if(null == cache_vGuid)
        {
            cache_vGuid = (byte[]) new byte[1];
            byte __var_1 = 0;
            ((byte[])cache_vGuid)[0] = __var_1;
        }
        setVGuid((byte []) _is.read(cache_vGuid, 1, false));

        if(null == cache_tUA)
        {
            cache_tUA = new com.duowan.Comm.AppUA();
        }
        setTUA((com.duowan.Comm.AppUA) _is.read(cache_tUA, 2, false));

        setSIMEI( _is.readString(3, false));

        setYyuid((long) _is.read(yyuid, 4, false));

        setSAPN( _is.readString(5, false));

        setSNetType( _is.readString(6, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(eType, "eType");
        _ds.display(vGuid, "vGuid");
        _ds.display(tUA, "tUA");
        _ds.display(sIMEI, "sIMEI");
        _ds.display(yyuid, "yyuid");
        _ds.display(sAPN, "sAPN");
        _ds.display(sNetType, "sNetType");
    }

}

