// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `CommBase.jce'
// **********************************************************************

package com.duowan.Comm;

public final class EPlatform
{
    private static EPlatform[] __values = new EPlatform[3];
    private int __value;
    private String __T = new String();

    public static final int _PLAT_INVALID = 0;
    public static final EPlatform PLAT_INVALID = new EPlatform(0,_PLAT_INVALID,"PLAT_INVALID");
    public static final int _PLAT_ADR = 1;
    public static final EPlatform PLAT_ADR = new EPlatform(1,_PLAT_ADR,"PLAT_ADR");
    public static final int _PLAT_IOS = 2;
    public static final EPlatform PLAT_IOS = new EPlatform(2,_PLAT_IOS,"PLAT_IOS");

    public static EPlatform convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static EPlatform convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private EPlatform(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
