// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `CommBase.jce'
// **********************************************************************

package com.duowan.Comm;

public final class LaunchRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "Comm.LaunchRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.Comm.LaunchRsp";
    }

    public byte [] vGuid = null;

    public int iTime = 0;

    public com.duowan.Comm.UpgradeRsp tUpgradeRsp = null;

    public java.util.ArrayList<String> vProxyList = null;

    public byte [] getVGuid()
    {
        return vGuid;
    }

    public void  setVGuid(byte [] vGuid)
    {
        this.vGuid = vGuid;
    }

    public int getITime()
    {
        return iTime;
    }

    public void  setITime(int iTime)
    {
        this.iTime = iTime;
    }

    public com.duowan.Comm.UpgradeRsp getTUpgradeRsp()
    {
        return tUpgradeRsp;
    }

    public void  setTUpgradeRsp(com.duowan.Comm.UpgradeRsp tUpgradeRsp)
    {
        this.tUpgradeRsp = tUpgradeRsp;
    }

    public java.util.ArrayList<String> getVProxyList()
    {
        return vProxyList;
    }

    public void  setVProxyList(java.util.ArrayList<String> vProxyList)
    {
        this.vProxyList = vProxyList;
    }

    public LaunchRsp()
    {
        setVGuid(vGuid);
        setITime(iTime);
        setTUpgradeRsp(tUpgradeRsp);
        setVProxyList(vProxyList);
    }

    public LaunchRsp(byte [] vGuid, int iTime, com.duowan.Comm.UpgradeRsp tUpgradeRsp, java.util.ArrayList<String> vProxyList)
    {
        setVGuid(vGuid);
        setITime(iTime);
        setTUpgradeRsp(tUpgradeRsp);
        setVProxyList(vProxyList);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        LaunchRsp t = (LaunchRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(vGuid, t.vGuid) && 
            com.duowan.taf.jce.JceUtil.equals(iTime, t.iTime) && 
            com.duowan.taf.jce.JceUtil.equals(tUpgradeRsp, t.tUpgradeRsp) && 
            com.duowan.taf.jce.JceUtil.equals(vProxyList, t.vProxyList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != vGuid)
        {
            _os.write(vGuid, 0);
        }
        _os.write(iTime, 1);
        if (null != tUpgradeRsp)
        {
            _os.write(tUpgradeRsp, 2);
        }
        if (null != vProxyList)
        {
            _os.write(vProxyList, 3);
        }
    }

    static byte [] cache_vGuid;
    static com.duowan.Comm.UpgradeRsp cache_tUpgradeRsp;
    static java.util.ArrayList<String> cache_vProxyList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_vGuid)
        {
            cache_vGuid = (byte[]) new byte[1];
            byte __var_2 = 0;
            ((byte[])cache_vGuid)[0] = __var_2;
        }
        setVGuid((byte []) _is.read(cache_vGuid, 0, false));

        setITime((int) _is.read(iTime, 1, false));

        if(null == cache_tUpgradeRsp)
        {
            cache_tUpgradeRsp = new com.duowan.Comm.UpgradeRsp();
        }
        setTUpgradeRsp((com.duowan.Comm.UpgradeRsp) _is.read(cache_tUpgradeRsp, 2, false));

        if(null == cache_vProxyList)
        {
            cache_vProxyList = new java.util.ArrayList<String>();
            String __var_3 = "";
            ((java.util.ArrayList<String>)cache_vProxyList).add(__var_3);
        }
        setVProxyList((java.util.ArrayList<String>) _is.read(cache_vProxyList, 3, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(vGuid, "vGuid");
        _ds.display(iTime, "iTime");
        _ds.display(tUpgradeRsp, "tUpgradeRsp");
        _ds.display(vProxyList, "vProxyList");
    }

}

