// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `CommBase.jce'
// **********************************************************************

package com.duowan.Comm;

public final class UpgradeReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "Comm.UpgradeReq";
    }

    public String fullClassName()
    {
        return "com.duowan.Comm.UpgradeReq";
    }

    public com.duowan.Comm.CommUserbase tUB = null;

    public int iUpgradeType = 0;

    public com.duowan.Comm.CommUserbase getTUB()
    {
        return tUB;
    }

    public void  setTUB(com.duowan.Comm.CommUserbase tUB)
    {
        this.tUB = tUB;
    }

    public int getIUpgradeType()
    {
        return iUpgradeType;
    }

    public void  setIUpgradeType(int iUpgradeType)
    {
        this.iUpgradeType = iUpgradeType;
    }

    public UpgradeReq()
    {
        setTUB(tUB);
        setIUpgradeType(iUpgradeType);
    }

    public UpgradeReq(com.duowan.Comm.CommUserbase tUB, int iUpgradeType)
    {
        setTUB(tUB);
        setIUpgradeType(iUpgradeType);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        UpgradeReq t = (UpgradeReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(tUB, t.tUB) && 
            com.duowan.taf.jce.JceUtil.equals(iUpgradeType, t.iUpgradeType) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != tUB)
        {
            _os.write(tUB, 0);
        }
        _os.write(iUpgradeType, 1);
    }

    static com.duowan.Comm.CommUserbase cache_tUB;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_tUB)
        {
            cache_tUB = new com.duowan.Comm.CommUserbase();
        }
        setTUB((com.duowan.Comm.CommUserbase) _is.read(cache_tUB, 0, false));

        setIUpgradeType((int) _is.read(iUpgradeType, 1, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(tUB, "tUB");
        _ds.display(iUpgradeType, "iUpgradeType");
    }

}

