// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `show.jce'
// **********************************************************************

package com.duowan.show;

public final class AddCommentReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "show.AddCommentReq";
    }

    public String fullClassName()
    {
        return "com.duowan.show.AddCommentReq";
    }

    public int topicId = 0;

    public String content = "";

    public String replyCommentId = "";

    public int getTopicId()
    {
        return topicId;
    }

    public void  setTopicId(int topicId)
    {
        this.topicId = topicId;
    }

    public String getContent()
    {
        return content;
    }

    public void  setContent(String content)
    {
        this.content = content;
    }

    public String getReplyCommentId()
    {
        return replyCommentId;
    }

    public void  setReplyCommentId(String replyCommentId)
    {
        this.replyCommentId = replyCommentId;
    }

    public AddCommentReq()
    {
        setTopicId(topicId);
        setContent(content);
        setReplyCommentId(replyCommentId);
    }

    public AddCommentReq(int topicId, String content, String replyCommentId)
    {
        setTopicId(topicId);
        setContent(content);
        setReplyCommentId(replyCommentId);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AddCommentReq t = (AddCommentReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(topicId, t.topicId) && 
            com.duowan.taf.jce.JceUtil.equals(content, t.content) && 
            com.duowan.taf.jce.JceUtil.equals(replyCommentId, t.replyCommentId) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(topicId, 0);
        if (null != content)
        {
            _os.write(content, 1);
        }
        if (null != replyCommentId)
        {
            _os.write(replyCommentId, 2);
        }
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setTopicId((int) _is.read(topicId, 0, false));

        setContent( _is.readString(1, false));

        setReplyCommentId( _is.readString(2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(topicId, "topicId");
        _ds.display(content, "content");
        _ds.display(replyCommentId, "replyCommentId");
    }

}

