// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `show.jce'
// **********************************************************************

package com.duowan.show;

public final class AdvInfo extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "show.AdvInfo";
    }

    public String fullClassName()
    {
        return "com.duowan.show.AdvInfo";
    }

    public String title = "";

    public String url = "";

    public String getTitle()
    {
        return title;
    }

    public void  setTitle(String title)
    {
        this.title = title;
    }

    public String getUrl()
    {
        return url;
    }

    public void  setUrl(String url)
    {
        this.url = url;
    }

    public AdvInfo()
    {
        setTitle(title);
        setUrl(url);
    }

    public AdvInfo(String title, String url)
    {
        setTitle(title);
        setUrl(url);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AdvInfo t = (AdvInfo) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(title, t.title) && 
            com.duowan.taf.jce.JceUtil.equals(url, t.url) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != title)
        {
            _os.write(title, 0);
        }
        if (null != url)
        {
            _os.write(url, 1);
        }
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setTitle( _is.readString(0, false));

        setUrl( _is.readString(1, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(title, "title");
        _ds.display(url, "url");
    }

}

