// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `show.jce'
// **********************************************************************

package com.duowan.show;

public final class AllowEmptyContent
{
    private static AllowEmptyContent[] __values = new AllowEmptyContent[2];
    private int __value;
    private String __T = new String();

    public static final int _ALLOW_EMPTY = 1;
    public static final AllowEmptyContent ALLOW_EMPTY = new AllowEmptyContent(0,_ALLOW_EMPTY,"ALLOW_EMPTY");
    public static final int _NO_ALLOW_EMPTY = 2;
    public static final AllowEmptyContent NO_ALLOW_EMPTY = new AllowEmptyContent(1,_NO_ALLOW_EMPTY,"NO_ALLOW_EMPTY");

    public static AllowEmptyContent convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static AllowEmptyContent convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private AllowEmptyContent(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
