// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `show.jce'
// **********************************************************************

package com.duowan.show;

public final class AppInitReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "show.AppInitReq";
    }

    public String fullClassName()
    {
        return "com.duowan.show.AppInitReq";
    }

    public int serviceType = 0;

    public int getServiceType()
    {
        return serviceType;
    }

    public void  setServiceType(int serviceType)
    {
        this.serviceType = serviceType;
    }

    public AppInitReq()
    {
        setServiceType(serviceType);
    }

    public AppInitReq(int serviceType)
    {
        setServiceType(serviceType);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AppInitReq t = (AppInitReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(serviceType, t.serviceType) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(serviceType, 0);
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setServiceType((int) _is.read(serviceType, 0, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(serviceType, "serviceType");
    }

}

