// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `show.jce'
// **********************************************************************

package com.duowan.show;

public final class BaseComment extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "show.BaseComment";
    }

    public String fullClassName()
    {
        return "com.duowan.show.BaseComment";
    }

    public String id = "";

    public String content = "";

    public int createTime = 0;

    public com.duowan.show.User author = null;

    public int likeNum = 0;

    public int disLikeNum = 0;

    public String getId()
    {
        return id;
    }

    public void  setId(String id)
    {
        this.id = id;
    }

    public String getContent()
    {
        return content;
    }

    public void  setContent(String content)
    {
        this.content = content;
    }

    public int getCreateTime()
    {
        return createTime;
    }

    public void  setCreateTime(int createTime)
    {
        this.createTime = createTime;
    }

    public com.duowan.show.User getAuthor()
    {
        return author;
    }

    public void  setAuthor(com.duowan.show.User author)
    {
        this.author = author;
    }

    public int getLikeNum()
    {
        return likeNum;
    }

    public void  setLikeNum(int likeNum)
    {
        this.likeNum = likeNum;
    }

    public int getDisLikeNum()
    {
        return disLikeNum;
    }

    public void  setDisLikeNum(int disLikeNum)
    {
        this.disLikeNum = disLikeNum;
    }

    public BaseComment()
    {
        setId(id);
        setContent(content);
        setCreateTime(createTime);
        setAuthor(author);
        setLikeNum(likeNum);
        setDisLikeNum(disLikeNum);
    }

    public BaseComment(String id, String content, int createTime, com.duowan.show.User author, int likeNum, int disLikeNum)
    {
        setId(id);
        setContent(content);
        setCreateTime(createTime);
        setAuthor(author);
        setLikeNum(likeNum);
        setDisLikeNum(disLikeNum);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        BaseComment t = (BaseComment) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(id, t.id) && 
            com.duowan.taf.jce.JceUtil.equals(content, t.content) && 
            com.duowan.taf.jce.JceUtil.equals(createTime, t.createTime) && 
            com.duowan.taf.jce.JceUtil.equals(author, t.author) && 
            com.duowan.taf.jce.JceUtil.equals(likeNum, t.likeNum) && 
            com.duowan.taf.jce.JceUtil.equals(disLikeNum, t.disLikeNum) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != id)
        {
            _os.write(id, 0);
        }
        if (null != content)
        {
            _os.write(content, 1);
        }
        _os.write(createTime, 2);
        if (null != author)
        {
            _os.write(author, 3);
        }
        _os.write(likeNum, 4);
        _os.write(disLikeNum, 5);
    }

    static com.duowan.show.User cache_author;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setId( _is.readString(0, false));

        setContent( _is.readString(1, false));

        setCreateTime((int) _is.read(createTime, 2, false));

        if(null == cache_author)
        {
            cache_author = new com.duowan.show.User();
        }
        setAuthor((com.duowan.show.User) _is.read(cache_author, 3, false));

        setLikeNum((int) _is.read(likeNum, 4, false));

        setDisLikeNum((int) _is.read(disLikeNum, 5, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(id, "id");
        _ds.display(content, "content");
        _ds.display(createTime, "createTime");
        _ds.display(author, "author");
        _ds.display(likeNum, "likeNum");
        _ds.display(disLikeNum, "disLikeNum");
    }

}

