// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `show.jce'
// **********************************************************************

package com.duowan.show;

public final class GetTopicListRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "show.GetTopicListRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.show.GetTopicListRsp";
    }

    public java.util.ArrayList<com.duowan.show.Topic> topicList = null;

    public String attachInfo = "";

    public boolean hasMore = true;

    public java.util.ArrayList<com.duowan.show.Topic> getTopicList()
    {
        return topicList;
    }

    public void  setTopicList(java.util.ArrayList<com.duowan.show.Topic> topicList)
    {
        this.topicList = topicList;
    }

    public String getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public boolean getHasMore()
    {
        return hasMore;
    }

    public void  setHasMore(boolean hasMore)
    {
        this.hasMore = hasMore;
    }

    public GetTopicListRsp()
    {
        setTopicList(topicList);
        setAttachInfo(attachInfo);
        setHasMore(hasMore);
    }

    public GetTopicListRsp(java.util.ArrayList<com.duowan.show.Topic> topicList, String attachInfo, boolean hasMore)
    {
        setTopicList(topicList);
        setAttachInfo(attachInfo);
        setHasMore(hasMore);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetTopicListRsp t = (GetTopicListRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(topicList, t.topicList) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) && 
            com.duowan.taf.jce.JceUtil.equals(hasMore, t.hasMore) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != topicList)
        {
            _os.write(topicList, 0);
        }
        if (null != attachInfo)
        {
            _os.write(attachInfo, 1);
        }
        _os.write(hasMore, 2);
    }

    static java.util.ArrayList<com.duowan.show.Topic> cache_topicList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_topicList)
        {
            cache_topicList = new java.util.ArrayList<com.duowan.show.Topic>();
            com.duowan.show.Topic __var_10 = new com.duowan.show.Topic();
            ((java.util.ArrayList<com.duowan.show.Topic>)cache_topicList).add(__var_10);
        }
        setTopicList((java.util.ArrayList<com.duowan.show.Topic>) _is.read(cache_topicList, 0, false));

        setAttachInfo( _is.readString(1, false));

        setHasMore((boolean) _is.read(hasMore, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(topicList, "topicList");
        _ds.display(attachInfo, "attachInfo");
        _ds.display(hasMore, "hasMore");
    }

}

