// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `show.jce'
// **********************************************************************

package com.duowan.show;

public final class Image extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "show.Image";
    }

    public String fullClassName()
    {
        return "com.duowan.show.Image";
    }

    public java.util.Map<Integer, com.duowan.show.PicInfo> image = null;

    public java.util.Map<Integer, com.duowan.show.PicInfo> getImage()
    {
        return image;
    }

    public void  setImage(java.util.Map<Integer, com.duowan.show.PicInfo> image)
    {
        this.image = image;
    }

    public Image()
    {
        setImage(image);
    }

    public Image(java.util.Map<Integer, com.duowan.show.PicInfo> image)
    {
        setImage(image);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        Image t = (Image) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(image, t.image) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != image)
        {
            _os.write(image, 0);
        }
    }

    static java.util.Map<Integer, com.duowan.show.PicInfo> cache_image;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_image)
        {
            cache_image = new java.util.HashMap<Integer, com.duowan.show.PicInfo>();
            Integer __var_1 = 0;
            com.duowan.show.PicInfo __var_2 = new com.duowan.show.PicInfo();
            cache_image.put(__var_1, __var_2);
        }
        setImage((java.util.Map<Integer, com.duowan.show.PicInfo>) _is.read(cache_image, 0, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(image, "image");
    }

}

