// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `show.jce'
// **********************************************************************

package com.duowan.show;

public final class NetEnvType
{
    private static NetEnvType[] __values = new NetEnvType[2];
    private int __value;
    private String __T = new String();

    public static final int _WIFI_ENV_TYPE = 1;
    public static final NetEnvType WIFI_ENV_TYPE = new NetEnvType(0,_WIFI_ENV_TYPE,"WIFI_ENV_TYPE");
    public static final int _NO_WIFI_ENV_TYPE = 2;
    public static final NetEnvType NO_WIFI_ENV_TYPE = new NetEnvType(1,_NO_WIFI_ENV_TYPE,"NO_WIFI_ENV_TYPE");

    public static NetEnvType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static NetEnvType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private NetEnvType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
