// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `show.jce'
// **********************************************************************

package com.duowan.show;

public final class NoteType
{
    private static NoteType[] __values = new NoteType[3];
    private int __value;
    private String __T = new String();

    public static final int _NOTE_COMMENT_TYPE = 1;
    public static final NoteType NOTE_COMMENT_TYPE = new NoteType(0,_NOTE_COMMENT_TYPE,"NOTE_COMMENT_TYPE");
    public static final int _NOTE_LIKE_TYPE = 2;
    public static final NoteType NOTE_LIKE_TYPE = new NoteType(1,_NOTE_LIKE_TYPE,"NOTE_LIKE_TYPE");
    public static final int _NOTE_REPPLY_TYPE = 3;
    public static final NoteType NOTE_REPPLY_TYPE = new NoteType(2,_NOTE_REPPLY_TYPE,"NOTE_REPPLY_TYPE");

    public static NoteType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static NoteType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private NoteType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
