// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `show.jce'
// **********************************************************************

package com.duowan.show;

public final class NotificationReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "show.NotificationReq";
    }

    public String fullClassName()
    {
        return "com.duowan.show.NotificationReq";
    }

    public int noteCallType = 0;

    public int refreshType = 0;

    public String attachInfo = "";

    public int getNoteCallType()
    {
        return noteCallType;
    }

    public void  setNoteCallType(int noteCallType)
    {
        this.noteCallType = noteCallType;
    }

    public int getRefreshType()
    {
        return refreshType;
    }

    public void  setRefreshType(int refreshType)
    {
        this.refreshType = refreshType;
    }

    public String getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public NotificationReq()
    {
        setNoteCallType(noteCallType);
        setRefreshType(refreshType);
        setAttachInfo(attachInfo);
    }

    public NotificationReq(int noteCallType, int refreshType, String attachInfo)
    {
        setNoteCallType(noteCallType);
        setRefreshType(refreshType);
        setAttachInfo(attachInfo);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        NotificationReq t = (NotificationReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(noteCallType, t.noteCallType) && 
            com.duowan.taf.jce.JceUtil.equals(refreshType, t.refreshType) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(noteCallType, 0);
        _os.write(refreshType, 1);
        if (null != attachInfo)
        {
            _os.write(attachInfo, 2);
        }
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setNoteCallType((int) _is.read(noteCallType, 0, false));

        setRefreshType((int) _is.read(refreshType, 1, false));

        setAttachInfo( _is.readString(2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(noteCallType, "noteCallType");
        _ds.display(refreshType, "refreshType");
        _ds.display(attachInfo, "attachInfo");
    }

}

