// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `show.jce'
// **********************************************************************

package com.duowan.show;

public final class ServiceType
{
    private static ServiceType[] __values = new ServiceType[1];
    private int __value;
    private String __T = new String();

    public static final int _SERVICE_ADV_TYPE = 1;
    public static final ServiceType SERVICE_ADV_TYPE = new ServiceType(0,_SERVICE_ADV_TYPE,"SERVICE_ADV_TYPE");

    public static ServiceType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static ServiceType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private ServiceType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
