// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `show.jce'
// **********************************************************************

package com.duowan.show;

public final class SpecialTagId
{
    private static SpecialTagId[] __values = new SpecialTagId[1];
    private int __value;
    private String __T = new String();

    public static final int _SPECIAL_TAGID_SQUARE = 100;
    public static final SpecialTagId SPECIAL_TAGID_SQUARE = new SpecialTagId(0,_SPECIAL_TAGID_SQUARE,"SPECIAL_TAGID_SQUARE");

    public static SpecialTagId convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static SpecialTagId convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private SpecialTagId(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
