// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `show.jce'
// **********************************************************************

package com.duowan.show;

public final class Topic extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "show.Topic";
    }

    public String fullClassName()
    {
        return "com.duowan.show.Topic";
    }

    public int id = 0;

    public int createTime = 0;

    public com.duowan.show.User author = null;

    public String desc = "";

    public com.duowan.show.Image image = null;

    public java.util.ArrayList<com.duowan.show.Tag> tagList = null;

    public int commentNum = 0;

    public int likeNum = 0;

    public int disLikeNum = 0;

    public boolean isLike = true;

    public int getId()
    {
        return id;
    }

    public void  setId(int id)
    {
        this.id = id;
    }

    public int getCreateTime()
    {
        return createTime;
    }

    public void  setCreateTime(int createTime)
    {
        this.createTime = createTime;
    }

    public com.duowan.show.User getAuthor()
    {
        return author;
    }

    public void  setAuthor(com.duowan.show.User author)
    {
        this.author = author;
    }

    public String getDesc()
    {
        return desc;
    }

    public void  setDesc(String desc)
    {
        this.desc = desc;
    }

    public com.duowan.show.Image getImage()
    {
        return image;
    }

    public void  setImage(com.duowan.show.Image image)
    {
        this.image = image;
    }

    public java.util.ArrayList<com.duowan.show.Tag> getTagList()
    {
        return tagList;
    }

    public void  setTagList(java.util.ArrayList<com.duowan.show.Tag> tagList)
    {
        this.tagList = tagList;
    }

    public int getCommentNum()
    {
        return commentNum;
    }

    public void  setCommentNum(int commentNum)
    {
        this.commentNum = commentNum;
    }

    public int getLikeNum()
    {
        return likeNum;
    }

    public void  setLikeNum(int likeNum)
    {
        this.likeNum = likeNum;
    }

    public int getDisLikeNum()
    {
        return disLikeNum;
    }

    public void  setDisLikeNum(int disLikeNum)
    {
        this.disLikeNum = disLikeNum;
    }

    public boolean getIsLike()
    {
        return isLike;
    }

    public void  setIsLike(boolean isLike)
    {
        this.isLike = isLike;
    }

    public Topic()
    {
        setId(id);
        setCreateTime(createTime);
        setAuthor(author);
        setDesc(desc);
        setImage(image);
        setTagList(tagList);
        setCommentNum(commentNum);
        setLikeNum(likeNum);
        setDisLikeNum(disLikeNum);
        setIsLike(isLike);
    }

    public Topic(int id, int createTime, com.duowan.show.User author, String desc, com.duowan.show.Image image, java.util.ArrayList<com.duowan.show.Tag> tagList, int commentNum, int likeNum, int disLikeNum, boolean isLike)
    {
        setId(id);
        setCreateTime(createTime);
        setAuthor(author);
        setDesc(desc);
        setImage(image);
        setTagList(tagList);
        setCommentNum(commentNum);
        setLikeNum(likeNum);
        setDisLikeNum(disLikeNum);
        setIsLike(isLike);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        Topic t = (Topic) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(id, t.id) && 
            com.duowan.taf.jce.JceUtil.equals(createTime, t.createTime) && 
            com.duowan.taf.jce.JceUtil.equals(author, t.author) && 
            com.duowan.taf.jce.JceUtil.equals(desc, t.desc) && 
            com.duowan.taf.jce.JceUtil.equals(image, t.image) && 
            com.duowan.taf.jce.JceUtil.equals(tagList, t.tagList) && 
            com.duowan.taf.jce.JceUtil.equals(commentNum, t.commentNum) && 
            com.duowan.taf.jce.JceUtil.equals(likeNum, t.likeNum) && 
            com.duowan.taf.jce.JceUtil.equals(disLikeNum, t.disLikeNum) && 
            com.duowan.taf.jce.JceUtil.equals(isLike, t.isLike) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(id, 0);
        _os.write(createTime, 1);
        if (null != author)
        {
            _os.write(author, 2);
        }
        if (null != desc)
        {
            _os.write(desc, 3);
        }
        if (null != image)
        {
            _os.write(image, 4);
        }
        if (null != tagList)
        {
            _os.write(tagList, 5);
        }
        _os.write(commentNum, 6);
        _os.write(likeNum, 7);
        _os.write(disLikeNum, 8);
        _os.write(isLike, 9);
    }

    static com.duowan.show.User cache_author;
    static com.duowan.show.Image cache_image;
    static java.util.ArrayList<com.duowan.show.Tag> cache_tagList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setId((int) _is.read(id, 0, false));

        setCreateTime((int) _is.read(createTime, 1, false));

        if(null == cache_author)
        {
            cache_author = new com.duowan.show.User();
        }
        setAuthor((com.duowan.show.User) _is.read(cache_author, 2, false));

        setDesc( _is.readString(3, false));

        if(null == cache_image)
        {
            cache_image = new com.duowan.show.Image();
        }
        setImage((com.duowan.show.Image) _is.read(cache_image, 4, false));

        if(null == cache_tagList)
        {
            cache_tagList = new java.util.ArrayList<com.duowan.show.Tag>();
            com.duowan.show.Tag __var_3 = new com.duowan.show.Tag();
            ((java.util.ArrayList<com.duowan.show.Tag>)cache_tagList).add(__var_3);
        }
        setTagList((java.util.ArrayList<com.duowan.show.Tag>) _is.read(cache_tagList, 5, false));

        setCommentNum((int) _is.read(commentNum, 6, false));

        setLikeNum((int) _is.read(likeNum, 7, false));

        setDisLikeNum((int) _is.read(disLikeNum, 8, false));

        setIsLike((boolean) _is.read(isLike, 9, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(id, "id");
        _ds.display(createTime, "createTime");
        _ds.display(author, "author");
        _ds.display(desc, "desc");
        _ds.display(image, "image");
        _ds.display(tagList, "tagList");
        _ds.display(commentNum, "commentNum");
        _ds.display(likeNum, "likeNum");
        _ds.display(disLikeNum, "disLikeNum");
        _ds.display(isLike, "isLike");
    }

}

