// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class ActiveInfo extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.ActiveInfo";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.ActiveInfo";
    }

    public int type = 0;

    public int id = 0;

    public String url = "";

    public String name = "";

    public String icon = "";

    public int is_new = 0;

    public int getType()
    {
        return type;
    }

    public void  setType(int type)
    {
        this.type = type;
    }

    public int getId()
    {
        return id;
    }

    public void  setId(int id)
    {
        this.id = id;
    }

    public String getUrl()
    {
        return url;
    }

    public void  setUrl(String url)
    {
        this.url = url;
    }

    public String getName()
    {
        return name;
    }

    public void  setName(String name)
    {
        this.name = name;
    }

    public String getIcon()
    {
        return icon;
    }

    public void  setIcon(String icon)
    {
        this.icon = icon;
    }

    public int getIs_new()
    {
        return is_new;
    }

    public void  setIs_new(int is_new)
    {
        this.is_new = is_new;
    }

    public ActiveInfo()
    {
        setType(type);
        setId(id);
        setUrl(url);
        setName(name);
        setIcon(icon);
        setIs_new(is_new);
    }

    public ActiveInfo(int type, int id, String url, String name, String icon, int is_new)
    {
        setType(type);
        setId(id);
        setUrl(url);
        setName(name);
        setIcon(icon);
        setIs_new(is_new);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ActiveInfo t = (ActiveInfo) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(type, t.type) && 
            com.duowan.taf.jce.JceUtil.equals(id, t.id) && 
            com.duowan.taf.jce.JceUtil.equals(url, t.url) && 
            com.duowan.taf.jce.JceUtil.equals(name, t.name) && 
            com.duowan.taf.jce.JceUtil.equals(icon, t.icon) && 
            com.duowan.taf.jce.JceUtil.equals(is_new, t.is_new) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(type, 0);
        _os.write(id, 1);
        if (null != url)
        {
            _os.write(url, 2);
        }
        if (null != name)
        {
            _os.write(name, 3);
        }
        if (null != icon)
        {
            _os.write(icon, 4);
        }
        _os.write(is_new, 5);
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setType((int) _is.read(type, 0, false));

        setId((int) _is.read(id, 1, false));

        setUrl( _is.readString(2, false));

        setName( _is.readString(3, false));

        setIcon( _is.readString(4, false));

        setIs_new((int) _is.read(is_new, 5, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(type, "type");
        _ds.display(id, "id");
        _ds.display(url, "url");
        _ds.display(name, "name");
        _ds.display(icon, "icon");
        _ds.display(is_new, "is_new");
    }

}

