// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class AddCommentReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.AddCommentReq";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.AddCommentReq";
    }

    public long articleId = 0;

    public String comment = "";

    public long getArticleId()
    {
        return articleId;
    }

    public void  setArticleId(long articleId)
    {
        this.articleId = articleId;
    }

    public String getComment()
    {
        return comment;
    }

    public void  setComment(String comment)
    {
        this.comment = comment;
    }

    public AddCommentReq()
    {
        setArticleId(articleId);
        setComment(comment);
    }

    public AddCommentReq(long articleId, String comment)
    {
        setArticleId(articleId);
        setComment(comment);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AddCommentReq t = (AddCommentReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(articleId, t.articleId) && 
            com.duowan.taf.jce.JceUtil.equals(comment, t.comment) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(articleId, 0);
        if (null != comment)
        {
            _os.write(comment, 1);
        }
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setArticleId((long) _is.read(articleId, 0, false));

        setComment( _is.readString(1, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(articleId, "articleId");
        _ds.display(comment, "comment");
    }

}

