// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class AddFavArticleReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.AddFavArticleReq";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.AddFavArticleReq";
    }

    public long articleId = 0;

    public int type = 0;

    public long getArticleId()
    {
        return articleId;
    }

    public void  setArticleId(long articleId)
    {
        this.articleId = articleId;
    }

    public int getType()
    {
        return type;
    }

    public void  setType(int type)
    {
        this.type = type;
    }

    public AddFavArticleReq()
    {
        setArticleId(articleId);
        setType(type);
    }

    public AddFavArticleReq(long articleId, int type)
    {
        setArticleId(articleId);
        setType(type);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AddFavArticleReq t = (AddFavArticleReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(articleId, t.articleId) && 
            com.duowan.taf.jce.JceUtil.equals(type, t.type) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(articleId, 0);
        _os.write(type, 1);
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setArticleId((long) _is.read(articleId, 0, false));

        setType((int) _is.read(type, 1, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(articleId, "articleId");
        _ds.display(type, "type");
    }

}

