// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class AdvIdInfo extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.AdvIdInfo";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.AdvIdInfo";
    }

    public String udId = "";

    public String idFa = "";

    public String macAddres = "";

    public String appId = "";

    public String getUdId()
    {
        return udId;
    }

    public void  setUdId(String udId)
    {
        this.udId = udId;
    }

    public String getIdFa()
    {
        return idFa;
    }

    public void  setIdFa(String idFa)
    {
        this.idFa = idFa;
    }

    public String getMacAddres()
    {
        return macAddres;
    }

    public void  setMacAddres(String macAddres)
    {
        this.macAddres = macAddres;
    }

    public String getAppId()
    {
        return appId;
    }

    public void  setAppId(String appId)
    {
        this.appId = appId;
    }

    public AdvIdInfo()
    {
        setUdId(udId);
        setIdFa(idFa);
        setMacAddres(macAddres);
        setAppId(appId);
    }

    public AdvIdInfo(String udId, String idFa, String macAddres, String appId)
    {
        setUdId(udId);
        setIdFa(idFa);
        setMacAddres(macAddres);
        setAppId(appId);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AdvIdInfo t = (AdvIdInfo) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(udId, t.udId) && 
            com.duowan.taf.jce.JceUtil.equals(idFa, t.idFa) && 
            com.duowan.taf.jce.JceUtil.equals(macAddres, t.macAddres) && 
            com.duowan.taf.jce.JceUtil.equals(appId, t.appId) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != udId)
        {
            _os.write(udId, 0);
        }
        if (null != idFa)
        {
            _os.write(idFa, 1);
        }
        if (null != macAddres)
        {
            _os.write(macAddres, 2);
        }
        if (null != appId)
        {
            _os.write(appId, 3);
        }
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setUdId( _is.readString(0, false));

        setIdFa( _is.readString(1, false));

        setMacAddres( _is.readString(2, false));

        setAppId( _is.readString(3, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(udId, "udId");
        _ds.display(idFa, "idFa");
        _ds.display(macAddres, "macAddres");
        _ds.display(appId, "appId");
    }

}

