// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class AppInitRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.AppInitRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.AppInitRsp";
    }

    public java.util.Map<String, java.util.ArrayList<String>> suggestionList = null;

    public java.util.ArrayList<com.duowan.gamenews.Channel> recommendList = null;

    public java.util.ArrayList<com.duowan.gamenews.Channel> activeList = null;

    public java.util.ArrayList<com.duowan.gamenews.Channel> TopList = null;

    public java.util.ArrayList<com.duowan.gamenews.ActiveInfo> newActiveList = null;

    public int flag = 0;

    public java.util.Map<Integer, String> options = null;

    public com.duowan.gamenews.ActiveInfo meActive = null;

    public java.util.Map<String, java.util.ArrayList<String>> getSuggestionList()
    {
        return suggestionList;
    }

    public void  setSuggestionList(java.util.Map<String, java.util.ArrayList<String>> suggestionList)
    {
        this.suggestionList = suggestionList;
    }

    public java.util.ArrayList<com.duowan.gamenews.Channel> getRecommendList()
    {
        return recommendList;
    }

    public void  setRecommendList(java.util.ArrayList<com.duowan.gamenews.Channel> recommendList)
    {
        this.recommendList = recommendList;
    }

    public java.util.ArrayList<com.duowan.gamenews.Channel> getActiveList()
    {
        return activeList;
    }

    public void  setActiveList(java.util.ArrayList<com.duowan.gamenews.Channel> activeList)
    {
        this.activeList = activeList;
    }

    public java.util.ArrayList<com.duowan.gamenews.Channel> getTopList()
    {
        return TopList;
    }

    public void  setTopList(java.util.ArrayList<com.duowan.gamenews.Channel> TopList)
    {
        this.TopList = TopList;
    }

    public java.util.ArrayList<com.duowan.gamenews.ActiveInfo> getNewActiveList()
    {
        return newActiveList;
    }

    public void  setNewActiveList(java.util.ArrayList<com.duowan.gamenews.ActiveInfo> newActiveList)
    {
        this.newActiveList = newActiveList;
    }

    public int getFlag()
    {
        return flag;
    }

    public void  setFlag(int flag)
    {
        this.flag = flag;
    }

    public java.util.Map<Integer, String> getOptions()
    {
        return options;
    }

    public void  setOptions(java.util.Map<Integer, String> options)
    {
        this.options = options;
    }

    public com.duowan.gamenews.ActiveInfo getMeActive()
    {
        return meActive;
    }

    public void  setMeActive(com.duowan.gamenews.ActiveInfo meActive)
    {
        this.meActive = meActive;
    }

    public AppInitRsp()
    {
        setSuggestionList(suggestionList);
        setRecommendList(recommendList);
        setActiveList(activeList);
        setTopList(TopList);
        setNewActiveList(newActiveList);
        setFlag(flag);
        setOptions(options);
        setMeActive(meActive);
    }

    public AppInitRsp(java.util.Map<String, java.util.ArrayList<String>> suggestionList, java.util.ArrayList<com.duowan.gamenews.Channel> recommendList, java.util.ArrayList<com.duowan.gamenews.Channel> activeList, java.util.ArrayList<com.duowan.gamenews.Channel> TopList, java.util.ArrayList<com.duowan.gamenews.ActiveInfo> newActiveList, int flag, java.util.Map<Integer, String> options, com.duowan.gamenews.ActiveInfo meActive)
    {
        setSuggestionList(suggestionList);
        setRecommendList(recommendList);
        setActiveList(activeList);
        setTopList(TopList);
        setNewActiveList(newActiveList);
        setFlag(flag);
        setOptions(options);
        setMeActive(meActive);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AppInitRsp t = (AppInitRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(suggestionList, t.suggestionList) && 
            com.duowan.taf.jce.JceUtil.equals(recommendList, t.recommendList) && 
            com.duowan.taf.jce.JceUtil.equals(activeList, t.activeList) && 
            com.duowan.taf.jce.JceUtil.equals(TopList, t.TopList) && 
            com.duowan.taf.jce.JceUtil.equals(newActiveList, t.newActiveList) && 
            com.duowan.taf.jce.JceUtil.equals(flag, t.flag) && 
            com.duowan.taf.jce.JceUtil.equals(options, t.options) && 
            com.duowan.taf.jce.JceUtil.equals(meActive, t.meActive) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != suggestionList)
        {
            _os.write(suggestionList, 0);
        }
        if (null != recommendList)
        {
            _os.write(recommendList, 1);
        }
        if (null != activeList)
        {
            _os.write(activeList, 2);
        }
        if (null != TopList)
        {
            _os.write(TopList, 3);
        }
        if (null != newActiveList)
        {
            _os.write(newActiveList, 4);
        }
        _os.write(flag, 5);
        if (null != options)
        {
            _os.write(options, 6);
        }
        if (null != meActive)
        {
            _os.write(meActive, 7);
        }
    }

    static java.util.Map<String, java.util.ArrayList<String>> cache_suggestionList;
    static java.util.ArrayList<com.duowan.gamenews.Channel> cache_recommendList;
    static java.util.ArrayList<com.duowan.gamenews.Channel> cache_activeList;
    static java.util.ArrayList<com.duowan.gamenews.Channel> cache_TopList;
    static java.util.ArrayList<com.duowan.gamenews.ActiveInfo> cache_newActiveList;
    static java.util.Map<Integer, String> cache_options;
    static com.duowan.gamenews.ActiveInfo cache_meActive;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_suggestionList)
        {
            cache_suggestionList = new java.util.HashMap<String, java.util.ArrayList<String>>();
            String __var_51 = "";
            java.util.ArrayList<String> __var_52 = new java.util.ArrayList<String>();
            String __var_53 = "";
            ((java.util.ArrayList<String>)__var_52).add(__var_53);
            cache_suggestionList.put(__var_51, __var_52);
        }
        setSuggestionList((java.util.Map<String, java.util.ArrayList<String>>) _is.read(cache_suggestionList, 0, false));

        if(null == cache_recommendList)
        {
            cache_recommendList = new java.util.ArrayList<com.duowan.gamenews.Channel>();
            com.duowan.gamenews.Channel __var_54 = new com.duowan.gamenews.Channel();
            ((java.util.ArrayList<com.duowan.gamenews.Channel>)cache_recommendList).add(__var_54);
        }
        setRecommendList((java.util.ArrayList<com.duowan.gamenews.Channel>) _is.read(cache_recommendList, 1, false));

        if(null == cache_activeList)
        {
            cache_activeList = new java.util.ArrayList<com.duowan.gamenews.Channel>();
            com.duowan.gamenews.Channel __var_55 = new com.duowan.gamenews.Channel();
            ((java.util.ArrayList<com.duowan.gamenews.Channel>)cache_activeList).add(__var_55);
        }
        setActiveList((java.util.ArrayList<com.duowan.gamenews.Channel>) _is.read(cache_activeList, 2, false));

        if(null == cache_TopList)
        {
            cache_TopList = new java.util.ArrayList<com.duowan.gamenews.Channel>();
            com.duowan.gamenews.Channel __var_56 = new com.duowan.gamenews.Channel();
            ((java.util.ArrayList<com.duowan.gamenews.Channel>)cache_TopList).add(__var_56);
        }
        setTopList((java.util.ArrayList<com.duowan.gamenews.Channel>) _is.read(cache_TopList, 3, false));

        if(null == cache_newActiveList)
        {
            cache_newActiveList = new java.util.ArrayList<com.duowan.gamenews.ActiveInfo>();
            com.duowan.gamenews.ActiveInfo __var_57 = new com.duowan.gamenews.ActiveInfo();
            ((java.util.ArrayList<com.duowan.gamenews.ActiveInfo>)cache_newActiveList).add(__var_57);
        }
        setNewActiveList((java.util.ArrayList<com.duowan.gamenews.ActiveInfo>) _is.read(cache_newActiveList, 4, false));

        setFlag((int) _is.read(flag, 5, false));

        if(null == cache_options)
        {
            cache_options = new java.util.HashMap<Integer, String>();
            Integer __var_58 = 0;
            String __var_59 = "";
            cache_options.put(__var_58, __var_59);
        }
        setOptions((java.util.Map<Integer, String>) _is.read(cache_options, 6, false));

        if(null == cache_meActive)
        {
            cache_meActive = new com.duowan.gamenews.ActiveInfo();
        }
        setMeActive((com.duowan.gamenews.ActiveInfo) _is.read(cache_meActive, 7, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(suggestionList, "suggestionList");
        _ds.display(recommendList, "recommendList");
        _ds.display(activeList, "activeList");
        _ds.display(TopList, "TopList");
        _ds.display(newActiveList, "newActiveList");
        _ds.display(flag, "flag");
        _ds.display(options, "options");
        _ds.display(meActive, "meActive");
    }

}

