// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class ArticleDetail extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.ArticleDetail";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.ArticleDetail";
    }

    public long id = 0;

    public String content = "";

    public java.util.ArrayList<com.duowan.gamenews.Image> imageList = null;

    public java.util.ArrayList<com.duowan.gamenews.Video> videoList = null;

    public java.util.ArrayList<com.duowan.gamenews.Channel> channelList = null;

    public String sourceUrl = "";

    public com.duowan.gamenews.Count count = null;

    public int commentCount = 0;

    public String title = "";

    public int timeStamp = 0;

    public String refer = "";

    public boolean hasFav = true;

    public int hasLike = 0;

    public long getId()
    {
        return id;
    }

    public void  setId(long id)
    {
        this.id = id;
    }

    public String getContent()
    {
        return content;
    }

    public void  setContent(String content)
    {
        this.content = content;
    }

    public java.util.ArrayList<com.duowan.gamenews.Image> getImageList()
    {
        return imageList;
    }

    public void  setImageList(java.util.ArrayList<com.duowan.gamenews.Image> imageList)
    {
        this.imageList = imageList;
    }

    public java.util.ArrayList<com.duowan.gamenews.Video> getVideoList()
    {
        return videoList;
    }

    public void  setVideoList(java.util.ArrayList<com.duowan.gamenews.Video> videoList)
    {
        this.videoList = videoList;
    }

    public java.util.ArrayList<com.duowan.gamenews.Channel> getChannelList()
    {
        return channelList;
    }

    public void  setChannelList(java.util.ArrayList<com.duowan.gamenews.Channel> channelList)
    {
        this.channelList = channelList;
    }

    public String getSourceUrl()
    {
        return sourceUrl;
    }

    public void  setSourceUrl(String sourceUrl)
    {
        this.sourceUrl = sourceUrl;
    }

    public com.duowan.gamenews.Count getCount()
    {
        return count;
    }

    public void  setCount(com.duowan.gamenews.Count count)
    {
        this.count = count;
    }

    public int getCommentCount()
    {
        return commentCount;
    }

    public void  setCommentCount(int commentCount)
    {
        this.commentCount = commentCount;
    }

    public String getTitle()
    {
        return title;
    }

    public void  setTitle(String title)
    {
        this.title = title;
    }

    public int getTimeStamp()
    {
        return timeStamp;
    }

    public void  setTimeStamp(int timeStamp)
    {
        this.timeStamp = timeStamp;
    }

    public String getRefer()
    {
        return refer;
    }

    public void  setRefer(String refer)
    {
        this.refer = refer;
    }

    public boolean getHasFav()
    {
        return hasFav;
    }

    public void  setHasFav(boolean hasFav)
    {
        this.hasFav = hasFav;
    }

    public int getHasLike()
    {
        return hasLike;
    }

    public void  setHasLike(int hasLike)
    {
        this.hasLike = hasLike;
    }

    public ArticleDetail()
    {
        setId(id);
        setContent(content);
        setImageList(imageList);
        setVideoList(videoList);
        setChannelList(channelList);
        setSourceUrl(sourceUrl);
        setCount(count);
        setCommentCount(commentCount);
        setTitle(title);
        setTimeStamp(timeStamp);
        setRefer(refer);
        setHasFav(hasFav);
        setHasLike(hasLike);
    }

    public ArticleDetail(long id, String content, java.util.ArrayList<com.duowan.gamenews.Image> imageList, java.util.ArrayList<com.duowan.gamenews.Video> videoList, java.util.ArrayList<com.duowan.gamenews.Channel> channelList, String sourceUrl, com.duowan.gamenews.Count count, int commentCount, String title, int timeStamp, String refer, boolean hasFav, int hasLike)
    {
        setId(id);
        setContent(content);
        setImageList(imageList);
        setVideoList(videoList);
        setChannelList(channelList);
        setSourceUrl(sourceUrl);
        setCount(count);
        setCommentCount(commentCount);
        setTitle(title);
        setTimeStamp(timeStamp);
        setRefer(refer);
        setHasFav(hasFav);
        setHasLike(hasLike);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        ArticleDetail t = (ArticleDetail) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(id, t.id) && 
            com.duowan.taf.jce.JceUtil.equals(content, t.content) && 
            com.duowan.taf.jce.JceUtil.equals(imageList, t.imageList) && 
            com.duowan.taf.jce.JceUtil.equals(videoList, t.videoList) && 
            com.duowan.taf.jce.JceUtil.equals(channelList, t.channelList) && 
            com.duowan.taf.jce.JceUtil.equals(sourceUrl, t.sourceUrl) && 
            com.duowan.taf.jce.JceUtil.equals(count, t.count) && 
            com.duowan.taf.jce.JceUtil.equals(commentCount, t.commentCount) && 
            com.duowan.taf.jce.JceUtil.equals(title, t.title) && 
            com.duowan.taf.jce.JceUtil.equals(timeStamp, t.timeStamp) && 
            com.duowan.taf.jce.JceUtil.equals(refer, t.refer) && 
            com.duowan.taf.jce.JceUtil.equals(hasFav, t.hasFav) && 
            com.duowan.taf.jce.JceUtil.equals(hasLike, t.hasLike) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(id, 0);
        if (null != content)
        {
            _os.write(content, 1);
        }
        if (null != imageList)
        {
            _os.write(imageList, 2);
        }
        if (null != videoList)
        {
            _os.write(videoList, 3);
        }
        if (null != channelList)
        {
            _os.write(channelList, 4);
        }
        if (null != sourceUrl)
        {
            _os.write(sourceUrl, 5);
        }
        if (null != count)
        {
            _os.write(count, 6);
        }
        _os.write(commentCount, 7);
        if (null != title)
        {
            _os.write(title, 8);
        }
        _os.write(timeStamp, 9);
        if (null != refer)
        {
            _os.write(refer, 10);
        }
        _os.write(hasFav, 11);
        _os.write(hasLike, 12);
    }

    static java.util.ArrayList<com.duowan.gamenews.Image> cache_imageList;
    static java.util.ArrayList<com.duowan.gamenews.Video> cache_videoList;
    static java.util.ArrayList<com.duowan.gamenews.Channel> cache_channelList;
    static com.duowan.gamenews.Count cache_count;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setId((long) _is.read(id, 0, false));

        setContent( _is.readString(1, false));

        if(null == cache_imageList)
        {
            cache_imageList = new java.util.ArrayList<com.duowan.gamenews.Image>();
            com.duowan.gamenews.Image __var_11 = new com.duowan.gamenews.Image();
            ((java.util.ArrayList<com.duowan.gamenews.Image>)cache_imageList).add(__var_11);
        }
        setImageList((java.util.ArrayList<com.duowan.gamenews.Image>) _is.read(cache_imageList, 2, false));

        if(null == cache_videoList)
        {
            cache_videoList = new java.util.ArrayList<com.duowan.gamenews.Video>();
            com.duowan.gamenews.Video __var_12 = new com.duowan.gamenews.Video();
            ((java.util.ArrayList<com.duowan.gamenews.Video>)cache_videoList).add(__var_12);
        }
        setVideoList((java.util.ArrayList<com.duowan.gamenews.Video>) _is.read(cache_videoList, 3, false));

        if(null == cache_channelList)
        {
            cache_channelList = new java.util.ArrayList<com.duowan.gamenews.Channel>();
            com.duowan.gamenews.Channel __var_13 = new com.duowan.gamenews.Channel();
            ((java.util.ArrayList<com.duowan.gamenews.Channel>)cache_channelList).add(__var_13);
        }
        setChannelList((java.util.ArrayList<com.duowan.gamenews.Channel>) _is.read(cache_channelList, 4, false));

        setSourceUrl( _is.readString(5, false));

        if(null == cache_count)
        {
            cache_count = new com.duowan.gamenews.Count();
        }
        setCount((com.duowan.gamenews.Count) _is.read(cache_count, 6, false));

        setCommentCount((int) _is.read(commentCount, 7, false));

        setTitle( _is.readString(8, false));

        setTimeStamp((int) _is.read(timeStamp, 9, false));

        setRefer( _is.readString(10, false));

        setHasFav((boolean) _is.read(hasFav, 11, false));

        setHasLike((int) _is.read(hasLike, 12, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(id, "id");
        _ds.display(content, "content");
        _ds.display(imageList, "imageList");
        _ds.display(videoList, "videoList");
        _ds.display(channelList, "channelList");
        _ds.display(sourceUrl, "sourceUrl");
        _ds.display(count, "count");
        _ds.display(commentCount, "commentCount");
        _ds.display(title, "title");
        _ds.display(timeStamp, "timeStamp");
        _ds.display(refer, "refer");
        _ds.display(hasFav, "hasFav");
        _ds.display(hasLike, "hasLike");
    }

}

