// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class ArticleType
{
    private static ArticleType[] __values = new ArticleType[12];
    private int __value;
    private String __T = new String();

    public static final int _ARTICLE_TYPE_ARTICLE = 1;
    public static final ArticleType ARTICLE_TYPE_ARTICLE = new ArticleType(0,_ARTICLE_TYPE_ARTICLE,"ARTICLE_TYPE_ARTICLE");
    public static final int _ARTICLE_TYPE_SPECIAL = 2;
    public static final ArticleType ARTICLE_TYPE_SPECIAL = new ArticleType(1,_ARTICLE_TYPE_SPECIAL,"ARTICLE_TYPE_SPECIAL");
    public static final int _ARTICLE_TYPE_CAIDAN = 3;
    public static final ArticleType ARTICLE_TYPE_CAIDAN = new ArticleType(2,_ARTICLE_TYPE_CAIDAN,"ARTICLE_TYPE_CAIDAN");
    public static final int _ARTICLE_TYPE_ACTIVITY = 4;
    public static final ArticleType ARTICLE_TYPE_ACTIVITY = new ArticleType(3,_ARTICLE_TYPE_ACTIVITY,"ARTICLE_TYPE_ACTIVITY");
    public static final int _ARTICLE_TYPE_BANG = 5;
    public static final ArticleType ARTICLE_TYPE_BANG = new ArticleType(4,_ARTICLE_TYPE_BANG,"ARTICLE_TYPE_BANG");
    public static final int _ARTICLE_TYPE_TEQUAN = 6;
    public static final ArticleType ARTICLE_TYPE_TEQUAN = new ArticleType(5,_ARTICLE_TYPE_TEQUAN,"ARTICLE_TYPE_TEQUAN");
    public static final int _ARTICLE_TYPE_CART_IMAGE_COLUMN = 7;
    public static final ArticleType ARTICLE_TYPE_CART_IMAGE_COLUMN = new ArticleType(6,_ARTICLE_TYPE_CART_IMAGE_COLUMN,"ARTICLE_TYPE_CART_IMAGE_COLUMN");
    public static final int _ARTICLE_TYPE_FALL = 8;
    public static final ArticleType ARTICLE_TYPE_FALL = new ArticleType(7,_ARTICLE_TYPE_FALL,"ARTICLE_TYPE_FALL");
    public static final int _ARTICLE_TYPE_VIDEO = 9;
    public static final ArticleType ARTICLE_TYPE_VIDEO = new ArticleType(8,_ARTICLE_TYPE_VIDEO,"ARTICLE_TYPE_VIDEO");
    public static final int _ARTICLE_TYPE_UNION_RACE = 10;
    public static final ArticleType ARTICLE_TYPE_UNION_RACE = new ArticleType(9,_ARTICLE_TYPE_UNION_RACE,"ARTICLE_TYPE_UNION_RACE");
    public static final int _ARTICLE_TYPE_PERSON_RACE = 11;
    public static final ArticleType ARTICLE_TYPE_PERSON_RACE = new ArticleType(10,_ARTICLE_TYPE_PERSON_RACE,"ARTICLE_TYPE_PERSON_RACE");
    public static final int _ARTICLE_TYPE_IMAGE = 12;
    public static final ArticleType ARTICLE_TYPE_IMAGE = new ArticleType(11,_ARTICLE_TYPE_IMAGE,"ARTICLE_TYPE_IMAGE");

    public static ArticleType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static ArticleType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private ArticleType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
