// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class ArticleFlag
{
    private static ArticleFlag[] __values = new ArticleFlag[12];
    private int __value;
    private String __T = new String();

    public static final int _ARTICLE_FLAG_BIGIMAGE = 1;
    public static final ArticleFlag ARTICLE_FLAG_BIGIMAGE = new ArticleFlag(0,_ARTICLE_FLAG_BIGIMAGE,"ARTICLE_FLAG_BIGIMAGE");
    public static final int _ARTICLE_FLAG_TOP = 2;
    public static final ArticleFlag ARTICLE_FLAG_TOP = new ArticleFlag(1,_ARTICLE_FLAG_TOP,"ARTICLE_FLAG_TOP");
    public static final int _ARTICLE_FLAG_RECOMM = 4;
    public static final ArticleFlag ARTICLE_FLAG_RECOMM = new ArticleFlag(2,_ARTICLE_FLAG_RECOMM,"ARTICLE_FLAG_RECOMM");
    public static final int _ARTICLE_FLAG_HOT = 8;
    public static final ArticleFlag ARTICLE_FLAG_HOT = new ArticleFlag(3,_ARTICLE_FLAG_HOT,"ARTICLE_FLAG_HOT");
    public static final int _ARTICLE_FLAG_ADV = 16;
    public static final ArticleFlag ARTICLE_FLAG_ADV = new ArticleFlag(4,_ARTICLE_FLAG_ADV,"ARTICLE_FLAG_ADV");
    public static final int _ARTICLE_FLAG_REDIRECT = 32;
    public static final ArticleFlag ARTICLE_FLAG_REDIRECT = new ArticleFlag(5,_ARTICLE_FLAG_REDIRECT,"ARTICLE_FLAG_REDIRECT");
    public static final int _ARTICLE_FLAG_NEWS = 1024;
    public static final ArticleFlag ARTICLE_FLAG_NEWS = new ArticleFlag(6,_ARTICLE_FLAG_NEWS,"ARTICLE_FLAG_NEWS");
    public static final int _ARTICLE_FLAG_VIDEO = 64;
    public static final ArticleFlag ARTICLE_FLAG_VIDEO = new ArticleFlag(7,_ARTICLE_FLAG_VIDEO,"ARTICLE_FLAG_VIDEO");
    public static final int _ARTICLE_FLAG_BIGIMAGE_WIDTH = 128;
    public static final ArticleFlag ARTICLE_FLAG_BIGIMAGE_WIDTH = new ArticleFlag(8,_ARTICLE_FLAG_BIGIMAGE_WIDTH,"ARTICLE_FLAG_BIGIMAGE_WIDTH");
    public static final int _ARTICLE_FLAG_BIGIMAGE_HEIGHT = 256;
    public static final ArticleFlag ARTICLE_FLAG_BIGIMAGE_HEIGHT = new ArticleFlag(9,_ARTICLE_FLAG_BIGIMAGE_HEIGHT,"ARTICLE_FLAG_BIGIMAGE_HEIGHT");
    public static final int _ARTICLE_FLAG_MORNING_PAPER = 512;
    public static final ArticleFlag ARTICLE_FLAG_MORNING_PAPER = new ArticleFlag(10,_ARTICLE_FLAG_MORNING_PAPER,"ARTICLE_FLAG_MORNING_PAPER");
    public static final int _ARTICLE_FLAG_EVENING_PAPER = 2048;
    public static final ArticleFlag ARTICLE_FLAG_EVENING_PAPER = new ArticleFlag(11,_ARTICLE_FLAG_EVENING_PAPER,"ARTICLE_FLAG_EVENING_PAPER");

    public static ArticleFlag convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static ArticleFlag convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private ArticleFlag(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
