// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class ButtonType
{
    private static ButtonType[] __values = new ButtonType[5];
    private int __value;
    private String __T = new String();

    public static final int _GO_USER_CENTER = 1;
    public static final ButtonType GO_USER_CENTER = new ButtonType(0,_GO_USER_CENTER,"GO_USER_CENTER");
    public static final int _GO_YY_LOGIN = 2;
    public static final ButtonType GO_YY_LOGIN = new ButtonType(1,_GO_YY_LOGIN,"GO_YY_LOGIN");
    public static final int _GO_WEB = 3;
    public static final ButtonType GO_WEB = new ButtonType(2,_GO_WEB,"GO_WEB");
    public static final int _GO_CANCEL = 4;
    public static final ButtonType GO_CANCEL = new ButtonType(3,_GO_CANCEL,"GO_CANCEL");
    public static final int _GO_CANCEL_MSG = 5;
    public static final ButtonType GO_CANCEL_MSG = new ButtonType(4,_GO_CANCEL_MSG,"GO_CANCEL_MSG");

    public static ButtonType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static ButtonType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private ButtonType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
