// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class ChannelType
{
    private static ChannelType[] __values = new ChannelType[3];
    private int __value;
    private String __T = new String();

    public static final int _CHANNEL_TYPE_NORMAL = 1;
    public static final ChannelType CHANNEL_TYPE_NORMAL = new ChannelType(0,_CHANNEL_TYPE_NORMAL,"CHANNEL_TYPE_NORMAL");
    public static final int _CHANNEL_TYPE_MULTI = 2;
    public static final ChannelType CHANNEL_TYPE_MULTI = new ChannelType(1,_CHANNEL_TYPE_MULTI,"CHANNEL_TYPE_MULTI");
    public static final int _CHANNEL_TYPE_FALL = 3;
    public static final ChannelType CHANNEL_TYPE_FALL = new ChannelType(2,_CHANNEL_TYPE_FALL,"CHANNEL_TYPE_FALL");

    public static ChannelType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static ChannelType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private ChannelType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
