// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class CheckInButton extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.CheckInButton";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.CheckInButton";
    }

    public String name = "";

    public String icon = "";

    public boolean isValid = true;

    public int checkInType = 0;

    public String getName()
    {
        return name;
    }

    public void  setName(String name)
    {
        this.name = name;
    }

    public String getIcon()
    {
        return icon;
    }

    public void  setIcon(String icon)
    {
        this.icon = icon;
    }

    public boolean getIsValid()
    {
        return isValid;
    }

    public void  setIsValid(boolean isValid)
    {
        this.isValid = isValid;
    }

    public int getCheckInType()
    {
        return checkInType;
    }

    public void  setCheckInType(int checkInType)
    {
        this.checkInType = checkInType;
    }

    public CheckInButton()
    {
        setName(name);
        setIcon(icon);
        setIsValid(isValid);
        setCheckInType(checkInType);
    }

    public CheckInButton(String name, String icon, boolean isValid, int checkInType)
    {
        setName(name);
        setIcon(icon);
        setIsValid(isValid);
        setCheckInType(checkInType);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        CheckInButton t = (CheckInButton) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(name, t.name) && 
            com.duowan.taf.jce.JceUtil.equals(icon, t.icon) && 
            com.duowan.taf.jce.JceUtil.equals(isValid, t.isValid) && 
            com.duowan.taf.jce.JceUtil.equals(checkInType, t.checkInType) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != name)
        {
            _os.write(name, 0);
        }
        if (null != icon)
        {
            _os.write(icon, 1);
        }
        _os.write(isValid, 2);
        _os.write(checkInType, 3);
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setName( _is.readString(0, false));

        setIcon( _is.readString(1, false));

        setIsValid((boolean) _is.read(isValid, 2, false));

        setCheckInType((int) _is.read(checkInType, 3, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(name, "name");
        _ds.display(icon, "icon");
        _ds.display(isValid, "isValid");
        _ds.display(checkInType, "checkInType");
    }

}

