// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class CheckInActionReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.CheckInActionReq";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.CheckInActionReq";
    }

    public int checkInType = 0;

    public String hash = "";

    public int platType = 0;

    public int getCheckInType()
    {
        return checkInType;
    }

    public void  setCheckInType(int checkInType)
    {
        this.checkInType = checkInType;
    }

    public String getHash()
    {
        return hash;
    }

    public void  setHash(String hash)
    {
        this.hash = hash;
    }

    public int getPlatType()
    {
        return platType;
    }

    public void  setPlatType(int platType)
    {
        this.platType = platType;
    }

    public CheckInActionReq()
    {
        setCheckInType(checkInType);
        setHash(hash);
        setPlatType(platType);
    }

    public CheckInActionReq(int checkInType, String hash, int platType)
    {
        setCheckInType(checkInType);
        setHash(hash);
        setPlatType(platType);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        CheckInActionReq t = (CheckInActionReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(checkInType, t.checkInType) && 
            com.duowan.taf.jce.JceUtil.equals(hash, t.hash) && 
            com.duowan.taf.jce.JceUtil.equals(platType, t.platType) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(checkInType, 0);
        if (null != hash)
        {
            _os.write(hash, 1);
        }
        _os.write(platType, 2);
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setCheckInType((int) _is.read(checkInType, 0, false));

        setHash( _is.readString(1, false));

        setPlatType((int) _is.read(platType, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(checkInType, "checkInType");
        _ds.display(hash, "hash");
        _ds.display(platType, "platType");
    }

}

