// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class CheckInIndexRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.CheckInIndexRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.CheckInIndexRsp";
    }

    public java.util.ArrayList<com.duowan.gamenews.CheckInButton> checkInButton = null;

    public String desc = "";

    public java.util.ArrayList<com.duowan.gamenews.Button> button = null;

    public java.util.ArrayList<com.duowan.gamenews.CheckInButton> getCheckInButton()
    {
        return checkInButton;
    }

    public void  setCheckInButton(java.util.ArrayList<com.duowan.gamenews.CheckInButton> checkInButton)
    {
        this.checkInButton = checkInButton;
    }

    public String getDesc()
    {
        return desc;
    }

    public void  setDesc(String desc)
    {
        this.desc = desc;
    }

    public java.util.ArrayList<com.duowan.gamenews.Button> getButton()
    {
        return button;
    }

    public void  setButton(java.util.ArrayList<com.duowan.gamenews.Button> button)
    {
        this.button = button;
    }

    public CheckInIndexRsp()
    {
        setCheckInButton(checkInButton);
        setDesc(desc);
        setButton(button);
    }

    public CheckInIndexRsp(java.util.ArrayList<com.duowan.gamenews.CheckInButton> checkInButton, String desc, java.util.ArrayList<com.duowan.gamenews.Button> button)
    {
        setCheckInButton(checkInButton);
        setDesc(desc);
        setButton(button);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        CheckInIndexRsp t = (CheckInIndexRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(checkInButton, t.checkInButton) && 
            com.duowan.taf.jce.JceUtil.equals(desc, t.desc) && 
            com.duowan.taf.jce.JceUtil.equals(button, t.button) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != checkInButton)
        {
            _os.write(checkInButton, 0);
        }
        if (null != desc)
        {
            _os.write(desc, 1);
        }
        if (null != button)
        {
            _os.write(button, 2);
        }
    }

    static java.util.ArrayList<com.duowan.gamenews.CheckInButton> cache_checkInButton;
    static java.util.ArrayList<com.duowan.gamenews.Button> cache_button;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_checkInButton)
        {
            cache_checkInButton = new java.util.ArrayList<com.duowan.gamenews.CheckInButton>();
            com.duowan.gamenews.CheckInButton __var_77 = new com.duowan.gamenews.CheckInButton();
            ((java.util.ArrayList<com.duowan.gamenews.CheckInButton>)cache_checkInButton).add(__var_77);
        }
        setCheckInButton((java.util.ArrayList<com.duowan.gamenews.CheckInButton>) _is.read(cache_checkInButton, 0, false));

        setDesc( _is.readString(1, false));

        if(null == cache_button)
        {
            cache_button = new java.util.ArrayList<com.duowan.gamenews.Button>();
            com.duowan.gamenews.Button __var_78 = new com.duowan.gamenews.Button();
            ((java.util.ArrayList<com.duowan.gamenews.Button>)cache_button).add(__var_78);
        }
        setButton((java.util.ArrayList<com.duowan.gamenews.Button>) _is.read(cache_button, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(checkInButton, "checkInButton");
        _ds.display(desc, "desc");
        _ds.display(button, "button");
    }

}

