// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class CheckInType
{
    private static CheckInType[] __values = new CheckInType[2];
    private int __value;
    private String __T = new String();

    public static final int _CHECKIN_TYPE_TDOU = 1;
    public static final CheckInType CHECKIN_TYPE_TDOU = new CheckInType(0,_CHECKIN_TYPE_TDOU,"CHECKIN_TYPE_TDOU");
    public static final int _CHECKIN_TYPE_QB = 2;
    public static final CheckInType CHECKIN_TYPE_QB = new CheckInType(1,_CHECKIN_TYPE_QB,"CHECKIN_TYPE_QB");

    public static CheckInType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static CheckInType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private CheckInType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
