// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class Column extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.Column";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.Column";
    }

    public int id = 0;

    public String name = "";

    public java.util.ArrayList<com.duowan.gamenews.Channel> channelList = null;

    public int getId()
    {
        return id;
    }

    public void  setId(int id)
    {
        this.id = id;
    }

    public String getName()
    {
        return name;
    }

    public void  setName(String name)
    {
        this.name = name;
    }

    public java.util.ArrayList<com.duowan.gamenews.Channel> getChannelList()
    {
        return channelList;
    }

    public void  setChannelList(java.util.ArrayList<com.duowan.gamenews.Channel> channelList)
    {
        this.channelList = channelList;
    }

    public Column()
    {
        setId(id);
        setName(name);
        setChannelList(channelList);
    }

    public Column(int id, String name, java.util.ArrayList<com.duowan.gamenews.Channel> channelList)
    {
        setId(id);
        setName(name);
        setChannelList(channelList);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        Column t = (Column) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(id, t.id) && 
            com.duowan.taf.jce.JceUtil.equals(name, t.name) && 
            com.duowan.taf.jce.JceUtil.equals(channelList, t.channelList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(id, 0);
        if (null != name)
        {
            _os.write(name, 1);
        }
        if (null != channelList)
        {
            _os.write(channelList, 2);
        }
    }

    static java.util.ArrayList<com.duowan.gamenews.Channel> cache_channelList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setId((int) _is.read(id, 0, false));

        setName( _is.readString(1, false));

        if(null == cache_channelList)
        {
            cache_channelList = new java.util.ArrayList<com.duowan.gamenews.Channel>();
            com.duowan.gamenews.Channel __var_2 = new com.duowan.gamenews.Channel();
            ((java.util.ArrayList<com.duowan.gamenews.Channel>)cache_channelList).add(__var_2);
        }
        setChannelList((java.util.ArrayList<com.duowan.gamenews.Channel>) _is.read(cache_channelList, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(id, "id");
        _ds.display(name, "name");
        _ds.display(channelList, "channelList");
    }

}

