// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class FeedBackReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.FeedBackReq";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.FeedBackReq";
    }

    public String content = "";

    public String platformInfo = "";

    public String appVersion = "";

    public String getContent()
    {
        return content;
    }

    public void  setContent(String content)
    {
        this.content = content;
    }

    public String getPlatformInfo()
    {
        return platformInfo;
    }

    public void  setPlatformInfo(String platformInfo)
    {
        this.platformInfo = platformInfo;
    }

    public String getAppVersion()
    {
        return appVersion;
    }

    public void  setAppVersion(String appVersion)
    {
        this.appVersion = appVersion;
    }

    public FeedBackReq()
    {
        setContent(content);
        setPlatformInfo(platformInfo);
        setAppVersion(appVersion);
    }

    public FeedBackReq(String content, String platformInfo, String appVersion)
    {
        setContent(content);
        setPlatformInfo(platformInfo);
        setAppVersion(appVersion);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        FeedBackReq t = (FeedBackReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(content, t.content) && 
            com.duowan.taf.jce.JceUtil.equals(platformInfo, t.platformInfo) && 
            com.duowan.taf.jce.JceUtil.equals(appVersion, t.appVersion) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != content)
        {
            _os.write(content, 0);
        }
        if (null != platformInfo)
        {
            _os.write(platformInfo, 1);
        }
        if (null != appVersion)
        {
            _os.write(appVersion, 2);
        }
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setContent( _is.readString(0, false));

        setPlatformInfo( _is.readString(1, false));

        setAppVersion( _is.readString(2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(content, "content");
        _ds.display(platformInfo, "platformInfo");
        _ds.display(appVersion, "appVersion");
    }

}

