// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetArticleDetailRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetArticleDetailRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetArticleDetailRsp";
    }

    public com.duowan.gamenews.ArticleDetail articleDetail = null;

    public java.util.Map<Integer, String> extraInfo = null;

    public com.duowan.gamenews.ArticleDetail getArticleDetail()
    {
        return articleDetail;
    }

    public void  setArticleDetail(com.duowan.gamenews.ArticleDetail articleDetail)
    {
        this.articleDetail = articleDetail;
    }

    public java.util.Map<Integer, String> getExtraInfo()
    {
        return extraInfo;
    }

    public void  setExtraInfo(java.util.Map<Integer, String> extraInfo)
    {
        this.extraInfo = extraInfo;
    }

    public GetArticleDetailRsp()
    {
        setArticleDetail(articleDetail);
        setExtraInfo(extraInfo);
    }

    public GetArticleDetailRsp(com.duowan.gamenews.ArticleDetail articleDetail, java.util.Map<Integer, String> extraInfo)
    {
        setArticleDetail(articleDetail);
        setExtraInfo(extraInfo);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetArticleDetailRsp t = (GetArticleDetailRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(articleDetail, t.articleDetail) && 
            com.duowan.taf.jce.JceUtil.equals(extraInfo, t.extraInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != articleDetail)
        {
            _os.write(articleDetail, 0);
        }
        if (null != extraInfo)
        {
            _os.write(extraInfo, 1);
        }
    }

    static com.duowan.gamenews.ArticleDetail cache_articleDetail;
    static java.util.Map<Integer, String> cache_extraInfo;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_articleDetail)
        {
            cache_articleDetail = new com.duowan.gamenews.ArticleDetail();
        }
        setArticleDetail((com.duowan.gamenews.ArticleDetail) _is.read(cache_articleDetail, 0, false));

        if(null == cache_extraInfo)
        {
            cache_extraInfo = new java.util.HashMap<Integer, String>();
            Integer __var_43 = 0;
            String __var_44 = "";
            cache_extraInfo.put(__var_43, __var_44);
        }
        setExtraInfo((java.util.Map<Integer, String>) _is.read(cache_extraInfo, 1, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(articleDetail, "articleDetail");
        _ds.display(extraInfo, "extraInfo");
    }

}

