// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetArticleDetailRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetArticleDetailRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetArticleDetailRsp";
    }

    public com.duowan.gamenews.ArticleDetail articleDetail = null;

    public java.util.Map<Integer, String> extraInfo = null;

    public java.util.ArrayList<com.duowan.gamenews.ArticleInfo> recommendList = null;

    public com.duowan.gamenews.ArticleDetail getArticleDetail()
    {
        return articleDetail;
    }

    public void  setArticleDetail(com.duowan.gamenews.ArticleDetail articleDetail)
    {
        this.articleDetail = articleDetail;
    }

    public java.util.Map<Integer, String> getExtraInfo()
    {
        return extraInfo;
    }

    public void  setExtraInfo(java.util.Map<Integer, String> extraInfo)
    {
        this.extraInfo = extraInfo;
    }

    public java.util.ArrayList<com.duowan.gamenews.ArticleInfo> getRecommendList()
    {
        return recommendList;
    }

    public void  setRecommendList(java.util.ArrayList<com.duowan.gamenews.ArticleInfo> recommendList)
    {
        this.recommendList = recommendList;
    }

    public GetArticleDetailRsp()
    {
        setArticleDetail(articleDetail);
        setExtraInfo(extraInfo);
        setRecommendList(recommendList);
    }

    public GetArticleDetailRsp(com.duowan.gamenews.ArticleDetail articleDetail, java.util.Map<Integer, String> extraInfo, java.util.ArrayList<com.duowan.gamenews.ArticleInfo> recommendList)
    {
        setArticleDetail(articleDetail);
        setExtraInfo(extraInfo);
        setRecommendList(recommendList);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetArticleDetailRsp t = (GetArticleDetailRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(articleDetail, t.articleDetail) && 
            com.duowan.taf.jce.JceUtil.equals(extraInfo, t.extraInfo) && 
            com.duowan.taf.jce.JceUtil.equals(recommendList, t.recommendList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != articleDetail)
        {
            _os.write(articleDetail, 0);
        }
        if (null != extraInfo)
        {
            _os.write(extraInfo, 1);
        }
        if (null != recommendList)
        {
            _os.write(recommendList, 2);
        }
    }

    static com.duowan.gamenews.ArticleDetail cache_articleDetail;
    static java.util.Map<Integer, String> cache_extraInfo;
    static java.util.ArrayList<com.duowan.gamenews.ArticleInfo> cache_recommendList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_articleDetail)
        {
            cache_articleDetail = new com.duowan.gamenews.ArticleDetail();
        }
        setArticleDetail((com.duowan.gamenews.ArticleDetail) _is.read(cache_articleDetail, 0, false));

        if(null == cache_extraInfo)
        {
            cache_extraInfo = new java.util.HashMap<Integer, String>();
            Integer __var_43 = 0;
            String __var_44 = "";
            cache_extraInfo.put(__var_43, __var_44);
        }
        setExtraInfo((java.util.Map<Integer, String>) _is.read(cache_extraInfo, 1, false));

        if(null == cache_recommendList)
        {
            cache_recommendList = new java.util.ArrayList<com.duowan.gamenews.ArticleInfo>();
            com.duowan.gamenews.ArticleInfo __var_45 = new com.duowan.gamenews.ArticleInfo();
            ((java.util.ArrayList<com.duowan.gamenews.ArticleInfo>)cache_recommendList).add(__var_45);
        }
        setRecommendList((java.util.ArrayList<com.duowan.gamenews.ArticleInfo>) _is.read(cache_recommendList, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(articleDetail, "articleDetail");
        _ds.display(extraInfo, "extraInfo");
        _ds.display(recommendList, "recommendList");
    }

}

