// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetChannelArticleListRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetChannelArticleListRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetChannelArticleListRsp";
    }

    public java.util.ArrayList<com.duowan.gamenews.ArticleInfo> articleList = null;

    public java.util.Map<Integer, String> attachInfo = null;

    public boolean hasMore = true;

    public int articleListType = 0;

    public java.util.ArrayList<com.duowan.gamenews.ArticleInfo> pictopList = null;

    public java.util.ArrayList<com.duowan.gamenews.HotChannel> hotChannel = null;

    public java.util.ArrayList<com.duowan.gamenews.ArticleInfo> getArticleList()
    {
        return articleList;
    }

    public void  setArticleList(java.util.ArrayList<com.duowan.gamenews.ArticleInfo> articleList)
    {
        this.articleList = articleList;
    }

    public java.util.Map<Integer, String> getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(java.util.Map<Integer, String> attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public boolean getHasMore()
    {
        return hasMore;
    }

    public void  setHasMore(boolean hasMore)
    {
        this.hasMore = hasMore;
    }

    public int getArticleListType()
    {
        return articleListType;
    }

    public void  setArticleListType(int articleListType)
    {
        this.articleListType = articleListType;
    }

    public java.util.ArrayList<com.duowan.gamenews.ArticleInfo> getPictopList()
    {
        return pictopList;
    }

    public void  setPictopList(java.util.ArrayList<com.duowan.gamenews.ArticleInfo> pictopList)
    {
        this.pictopList = pictopList;
    }

    public java.util.ArrayList<com.duowan.gamenews.HotChannel> getHotChannel()
    {
        return hotChannel;
    }

    public void  setHotChannel(java.util.ArrayList<com.duowan.gamenews.HotChannel> hotChannel)
    {
        this.hotChannel = hotChannel;
    }

    public GetChannelArticleListRsp()
    {
        setArticleList(articleList);
        setAttachInfo(attachInfo);
        setHasMore(hasMore);
        setArticleListType(articleListType);
        setPictopList(pictopList);
        setHotChannel(hotChannel);
    }

    public GetChannelArticleListRsp(java.util.ArrayList<com.duowan.gamenews.ArticleInfo> articleList, java.util.Map<Integer, String> attachInfo, boolean hasMore, int articleListType, java.util.ArrayList<com.duowan.gamenews.ArticleInfo> pictopList, java.util.ArrayList<com.duowan.gamenews.HotChannel> hotChannel)
    {
        setArticleList(articleList);
        setAttachInfo(attachInfo);
        setHasMore(hasMore);
        setArticleListType(articleListType);
        setPictopList(pictopList);
        setHotChannel(hotChannel);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetChannelArticleListRsp t = (GetChannelArticleListRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(articleList, t.articleList) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) && 
            com.duowan.taf.jce.JceUtil.equals(hasMore, t.hasMore) && 
            com.duowan.taf.jce.JceUtil.equals(articleListType, t.articleListType) && 
            com.duowan.taf.jce.JceUtil.equals(pictopList, t.pictopList) && 
            com.duowan.taf.jce.JceUtil.equals(hotChannel, t.hotChannel) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != articleList)
        {
            _os.write(articleList, 0);
        }
        if (null != attachInfo)
        {
            _os.write(attachInfo, 1);
        }
        _os.write(hasMore, 2);
        _os.write(articleListType, 3);
        if (null != pictopList)
        {
            _os.write(pictopList, 4);
        }
        if (null != hotChannel)
        {
            _os.write(hotChannel, 5);
        }
    }

    static java.util.ArrayList<com.duowan.gamenews.ArticleInfo> cache_articleList;
    static java.util.Map<Integer, String> cache_attachInfo;
    static java.util.ArrayList<com.duowan.gamenews.ArticleInfo> cache_pictopList;
    static java.util.ArrayList<com.duowan.gamenews.HotChannel> cache_hotChannel;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_articleList)
        {
            cache_articleList = new java.util.ArrayList<com.duowan.gamenews.ArticleInfo>();
            com.duowan.gamenews.ArticleInfo __var_32 = new com.duowan.gamenews.ArticleInfo();
            ((java.util.ArrayList<com.duowan.gamenews.ArticleInfo>)cache_articleList).add(__var_32);
        }
        setArticleList((java.util.ArrayList<com.duowan.gamenews.ArticleInfo>) _is.read(cache_articleList, 0, false));

        if(null == cache_attachInfo)
        {
            cache_attachInfo = new java.util.HashMap<Integer, String>();
            Integer __var_33 = 0;
            String __var_34 = "";
            cache_attachInfo.put(__var_33, __var_34);
        }
        setAttachInfo((java.util.Map<Integer, String>) _is.read(cache_attachInfo, 1, false));

        setHasMore((boolean) _is.read(hasMore, 2, false));

        setArticleListType((int) _is.read(articleListType, 3, false));

        if(null == cache_pictopList)
        {
            cache_pictopList = new java.util.ArrayList<com.duowan.gamenews.ArticleInfo>();
            com.duowan.gamenews.ArticleInfo __var_35 = new com.duowan.gamenews.ArticleInfo();
            ((java.util.ArrayList<com.duowan.gamenews.ArticleInfo>)cache_pictopList).add(__var_35);
        }
        setPictopList((java.util.ArrayList<com.duowan.gamenews.ArticleInfo>) _is.read(cache_pictopList, 4, false));

        if(null == cache_hotChannel)
        {
            cache_hotChannel = new java.util.ArrayList<com.duowan.gamenews.HotChannel>();
            com.duowan.gamenews.HotChannel __var_36 = new com.duowan.gamenews.HotChannel();
            ((java.util.ArrayList<com.duowan.gamenews.HotChannel>)cache_hotChannel).add(__var_36);
        }
        setHotChannel((java.util.ArrayList<com.duowan.gamenews.HotChannel>) _is.read(cache_hotChannel, 5, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(articleList, "articleList");
        _ds.display(attachInfo, "attachInfo");
        _ds.display(hasMore, "hasMore");
        _ds.display(articleListType, "articleListType");
        _ds.display(pictopList, "pictopList");
        _ds.display(hotChannel, "hotChannel");
    }

}

