// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetChannelDetailRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetChannelDetailRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetChannelDetailRsp";
    }

    public com.duowan.gamenews.Channel channelInfo = null;

    public com.duowan.gamenews.Channel getChannelInfo()
    {
        return channelInfo;
    }

    public void  setChannelInfo(com.duowan.gamenews.Channel channelInfo)
    {
        this.channelInfo = channelInfo;
    }

    public GetChannelDetailRsp()
    {
        setChannelInfo(channelInfo);
    }

    public GetChannelDetailRsp(com.duowan.gamenews.Channel channelInfo)
    {
        setChannelInfo(channelInfo);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetChannelDetailRsp t = (GetChannelDetailRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(channelInfo, t.channelInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != channelInfo)
        {
            _os.write(channelInfo, 0);
        }
    }

    static com.duowan.gamenews.Channel cache_channelInfo;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_channelInfo)
        {
            cache_channelInfo = new com.duowan.gamenews.Channel();
        }
        setChannelInfo((com.duowan.gamenews.Channel) _is.read(cache_channelInfo, 0, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(channelInfo, "channelInfo");
    }

}

