// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetColumnListRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetColumnListRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetColumnListRsp";
    }

    public java.util.ArrayList<com.duowan.gamenews.Column> columnList = null;

    public String attachInfo = "";

    public boolean hasMore = true;

    public java.util.ArrayList<com.duowan.gamenews.Column> getColumnList()
    {
        return columnList;
    }

    public void  setColumnList(java.util.ArrayList<com.duowan.gamenews.Column> columnList)
    {
        this.columnList = columnList;
    }

    public String getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public boolean getHasMore()
    {
        return hasMore;
    }

    public void  setHasMore(boolean hasMore)
    {
        this.hasMore = hasMore;
    }

    public GetColumnListRsp()
    {
        setColumnList(columnList);
        setAttachInfo(attachInfo);
        setHasMore(hasMore);
    }

    public GetColumnListRsp(java.util.ArrayList<com.duowan.gamenews.Column> columnList, String attachInfo, boolean hasMore)
    {
        setColumnList(columnList);
        setAttachInfo(attachInfo);
        setHasMore(hasMore);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetColumnListRsp t = (GetColumnListRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(columnList, t.columnList) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) && 
            com.duowan.taf.jce.JceUtil.equals(hasMore, t.hasMore) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != columnList)
        {
            _os.write(columnList, 0);
        }
        if (null != attachInfo)
        {
            _os.write(attachInfo, 1);
        }
        _os.write(hasMore, 2);
    }

    static java.util.ArrayList<com.duowan.gamenews.Column> cache_columnList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_columnList)
        {
            cache_columnList = new java.util.ArrayList<com.duowan.gamenews.Column>();
            com.duowan.gamenews.Column __var_20 = new com.duowan.gamenews.Column();
            ((java.util.ArrayList<com.duowan.gamenews.Column>)cache_columnList).add(__var_20);
        }
        setColumnList((java.util.ArrayList<com.duowan.gamenews.Column>) _is.read(cache_columnList, 0, false));

        setAttachInfo( _is.readString(1, false));

        setHasMore((boolean) _is.read(hasMore, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(columnList, "columnList");
        _ds.display(attachInfo, "attachInfo");
        _ds.display(hasMore, "hasMore");
    }

}

