// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetChannelArticleListReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetChannelArticleListReq";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetChannelArticleListReq";
    }

    public int channelId = 0;

    public int refreshType = 0;

    public java.util.Map<Integer, String> attachInfo = null;

    public int count = 0;

    public int subChannelId = 0;

    public int subType = 0;

    public int getChannelId()
    {
        return channelId;
    }

    public void  setChannelId(int channelId)
    {
        this.channelId = channelId;
    }

    public int getRefreshType()
    {
        return refreshType;
    }

    public void  setRefreshType(int refreshType)
    {
        this.refreshType = refreshType;
    }

    public java.util.Map<Integer, String> getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(java.util.Map<Integer, String> attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public int getCount()
    {
        return count;
    }

    public void  setCount(int count)
    {
        this.count = count;
    }

    public int getSubChannelId()
    {
        return subChannelId;
    }

    public void  setSubChannelId(int subChannelId)
    {
        this.subChannelId = subChannelId;
    }

    public int getSubType()
    {
        return subType;
    }

    public void  setSubType(int subType)
    {
        this.subType = subType;
    }

    public GetChannelArticleListReq()
    {
        setChannelId(channelId);
        setRefreshType(refreshType);
        setAttachInfo(attachInfo);
        setCount(count);
        setSubChannelId(subChannelId);
        setSubType(subType);
    }

    public GetChannelArticleListReq(int channelId, int refreshType, java.util.Map<Integer, String> attachInfo, int count, int subChannelId, int subType)
    {
        setChannelId(channelId);
        setRefreshType(refreshType);
        setAttachInfo(attachInfo);
        setCount(count);
        setSubChannelId(subChannelId);
        setSubType(subType);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetChannelArticleListReq t = (GetChannelArticleListReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(channelId, t.channelId) && 
            com.duowan.taf.jce.JceUtil.equals(refreshType, t.refreshType) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) && 
            com.duowan.taf.jce.JceUtil.equals(count, t.count) && 
            com.duowan.taf.jce.JceUtil.equals(subChannelId, t.subChannelId) && 
            com.duowan.taf.jce.JceUtil.equals(subType, t.subType) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(channelId, 0);
        _os.write(refreshType, 1);
        if (null != attachInfo)
        {
            _os.write(attachInfo, 2);
        }
        _os.write(count, 3);
        _os.write(subChannelId, 4);
        _os.write(subType, 5);
    }

    static java.util.Map<Integer, String> cache_attachInfo;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setChannelId((int) _is.read(channelId, 0, false));

        setRefreshType((int) _is.read(refreshType, 1, false));

        if(null == cache_attachInfo)
        {
            cache_attachInfo = new java.util.HashMap<Integer, String>();
            Integer __var_30 = 0;
            String __var_31 = "";
            cache_attachInfo.put(__var_30, __var_31);
        }
        setAttachInfo((java.util.Map<Integer, String>) _is.read(cache_attachInfo, 2, false));

        setCount((int) _is.read(count, 3, false));

        setSubChannelId((int) _is.read(subChannelId, 4, false));

        setSubType((int) _is.read(subType, 5, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(channelId, "channelId");
        _ds.display(refreshType, "refreshType");
        _ds.display(attachInfo, "attachInfo");
        _ds.display(count, "count");
        _ds.display(subChannelId, "subChannelId");
        _ds.display(subType, "subType");
    }

}

