// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetRaceTopicReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetRaceTopicReq";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetRaceTopicReq";
    }

    public long topicId = 0;

    public String attachInfo = "";

    public int refreshType = 0;

    public long getTopicId()
    {
        return topicId;
    }

    public void  setTopicId(long topicId)
    {
        this.topicId = topicId;
    }

    public String getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public int getRefreshType()
    {
        return refreshType;
    }

    public void  setRefreshType(int refreshType)
    {
        this.refreshType = refreshType;
    }

    public GetRaceTopicReq()
    {
        setTopicId(topicId);
        setAttachInfo(attachInfo);
        setRefreshType(refreshType);
    }

    public GetRaceTopicReq(long topicId, String attachInfo, int refreshType)
    {
        setTopicId(topicId);
        setAttachInfo(attachInfo);
        setRefreshType(refreshType);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetRaceTopicReq t = (GetRaceTopicReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(topicId, t.topicId) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) && 
            com.duowan.taf.jce.JceUtil.equals(refreshType, t.refreshType) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(topicId, 0);
        if (null != attachInfo)
        {
            _os.write(attachInfo, 1);
        }
        _os.write(refreshType, 2);
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setTopicId((long) _is.read(topicId, 0, false));

        setAttachInfo( _is.readString(1, false));

        setRefreshType((int) _is.read(refreshType, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(topicId, "topicId");
        _ds.display(attachInfo, "attachInfo");
        _ds.display(refreshType, "refreshType");
    }

}

