// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetRecommendArticleListRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetRecommendArticleListRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetRecommendArticleListRsp";
    }

    public java.util.ArrayList<com.duowan.gamenews.ArticleInfo> articleList = null;

    public java.util.ArrayList<com.duowan.gamenews.ArticleInfo> getArticleList()
    {
        return articleList;
    }

    public void  setArticleList(java.util.ArrayList<com.duowan.gamenews.ArticleInfo> articleList)
    {
        this.articleList = articleList;
    }

    public GetRecommendArticleListRsp()
    {
        setArticleList(articleList);
    }

    public GetRecommendArticleListRsp(java.util.ArrayList<com.duowan.gamenews.ArticleInfo> articleList)
    {
        setArticleList(articleList);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetRecommendArticleListRsp t = (GetRecommendArticleListRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(articleList, t.articleList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != articleList)
        {
            _os.write(articleList, 0);
        }
    }

    static java.util.ArrayList<com.duowan.gamenews.ArticleInfo> cache_articleList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_articleList)
        {
            cache_articleList = new java.util.ArrayList<com.duowan.gamenews.ArticleInfo>();
            com.duowan.gamenews.ArticleInfo __var_81 = new com.duowan.gamenews.ArticleInfo();
            ((java.util.ArrayList<com.duowan.gamenews.ArticleInfo>)cache_articleList).add(__var_81);
        }
        setArticleList((java.util.ArrayList<com.duowan.gamenews.ArticleInfo>) _is.read(cache_articleList, 0, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(articleList, "articleList");
    }

}

