// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetRaceTopicRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetRaceTopicRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetRaceTopicRsp";
    }

    public java.util.ArrayList<com.duowan.gamenews.UnionInfo> unionList = null;

    public String title = "";

    public String summary = "";

    public int heat = 0;

    public String img = "";

    public String subTitle = "";

    public String underDesc = "";

    public java.util.ArrayList<com.duowan.gamenews.ArticleInfo> articleList = null;

    public boolean hasMore = true;

    public String attachInfo = "";

    public java.util.ArrayList<com.duowan.gamenews.UnionInfo> getUnionList()
    {
        return unionList;
    }

    public void  setUnionList(java.util.ArrayList<com.duowan.gamenews.UnionInfo> unionList)
    {
        this.unionList = unionList;
    }

    public String getTitle()
    {
        return title;
    }

    public void  setTitle(String title)
    {
        this.title = title;
    }

    public String getSummary()
    {
        return summary;
    }

    public void  setSummary(String summary)
    {
        this.summary = summary;
    }

    public int getHeat()
    {
        return heat;
    }

    public void  setHeat(int heat)
    {
        this.heat = heat;
    }

    public String getImg()
    {
        return img;
    }

    public void  setImg(String img)
    {
        this.img = img;
    }

    public String getSubTitle()
    {
        return subTitle;
    }

    public void  setSubTitle(String subTitle)
    {
        this.subTitle = subTitle;
    }

    public String getUnderDesc()
    {
        return underDesc;
    }

    public void  setUnderDesc(String underDesc)
    {
        this.underDesc = underDesc;
    }

    public java.util.ArrayList<com.duowan.gamenews.ArticleInfo> getArticleList()
    {
        return articleList;
    }

    public void  setArticleList(java.util.ArrayList<com.duowan.gamenews.ArticleInfo> articleList)
    {
        this.articleList = articleList;
    }

    public boolean getHasMore()
    {
        return hasMore;
    }

    public void  setHasMore(boolean hasMore)
    {
        this.hasMore = hasMore;
    }

    public String getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public GetRaceTopicRsp()
    {
        setUnionList(unionList);
        setTitle(title);
        setSummary(summary);
        setHeat(heat);
        setImg(img);
        setSubTitle(subTitle);
        setUnderDesc(underDesc);
        setArticleList(articleList);
        setHasMore(hasMore);
        setAttachInfo(attachInfo);
    }

    public GetRaceTopicRsp(java.util.ArrayList<com.duowan.gamenews.UnionInfo> unionList, String title, String summary, int heat, String img, String subTitle, String underDesc, java.util.ArrayList<com.duowan.gamenews.ArticleInfo> articleList, boolean hasMore, String attachInfo)
    {
        setUnionList(unionList);
        setTitle(title);
        setSummary(summary);
        setHeat(heat);
        setImg(img);
        setSubTitle(subTitle);
        setUnderDesc(underDesc);
        setArticleList(articleList);
        setHasMore(hasMore);
        setAttachInfo(attachInfo);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetRaceTopicRsp t = (GetRaceTopicRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(unionList, t.unionList) && 
            com.duowan.taf.jce.JceUtil.equals(title, t.title) && 
            com.duowan.taf.jce.JceUtil.equals(summary, t.summary) && 
            com.duowan.taf.jce.JceUtil.equals(heat, t.heat) && 
            com.duowan.taf.jce.JceUtil.equals(img, t.img) && 
            com.duowan.taf.jce.JceUtil.equals(subTitle, t.subTitle) && 
            com.duowan.taf.jce.JceUtil.equals(underDesc, t.underDesc) && 
            com.duowan.taf.jce.JceUtil.equals(articleList, t.articleList) && 
            com.duowan.taf.jce.JceUtil.equals(hasMore, t.hasMore) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != unionList)
        {
            _os.write(unionList, 0);
        }
        if (null != title)
        {
            _os.write(title, 1);
        }
        if (null != summary)
        {
            _os.write(summary, 2);
        }
        _os.write(heat, 3);
        if (null != img)
        {
            _os.write(img, 4);
        }
        if (null != subTitle)
        {
            _os.write(subTitle, 5);
        }
        if (null != underDesc)
        {
            _os.write(underDesc, 6);
        }
        if (null != articleList)
        {
            _os.write(articleList, 7);
        }
        _os.write(hasMore, 8);
        if (null != attachInfo)
        {
            _os.write(attachInfo, 9);
        }
    }

    static java.util.ArrayList<com.duowan.gamenews.UnionInfo> cache_unionList;
    static java.util.ArrayList<com.duowan.gamenews.ArticleInfo> cache_articleList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_unionList)
        {
            cache_unionList = new java.util.ArrayList<com.duowan.gamenews.UnionInfo>();
            com.duowan.gamenews.UnionInfo __var_75 = new com.duowan.gamenews.UnionInfo();
            ((java.util.ArrayList<com.duowan.gamenews.UnionInfo>)cache_unionList).add(__var_75);
        }
        setUnionList((java.util.ArrayList<com.duowan.gamenews.UnionInfo>) _is.read(cache_unionList, 0, false));

        setTitle( _is.readString(1, false));

        setSummary( _is.readString(2, false));

        setHeat((int) _is.read(heat, 3, false));

        setImg( _is.readString(4, false));

        setSubTitle( _is.readString(5, false));

        setUnderDesc( _is.readString(6, false));

        if(null == cache_articleList)
        {
            cache_articleList = new java.util.ArrayList<com.duowan.gamenews.ArticleInfo>();
            com.duowan.gamenews.ArticleInfo __var_76 = new com.duowan.gamenews.ArticleInfo();
            ((java.util.ArrayList<com.duowan.gamenews.ArticleInfo>)cache_articleList).add(__var_76);
        }
        setArticleList((java.util.ArrayList<com.duowan.gamenews.ArticleInfo>) _is.read(cache_articleList, 7, false));

        setHasMore((boolean) _is.read(hasMore, 8, false));

        setAttachInfo( _is.readString(9, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(unionList, "unionList");
        _ds.display(title, "title");
        _ds.display(summary, "summary");
        _ds.display(heat, "heat");
        _ds.display(img, "img");
        _ds.display(subTitle, "subTitle");
        _ds.display(underDesc, "underDesc");
        _ds.display(articleList, "articleList");
        _ds.display(hasMore, "hasMore");
        _ds.display(attachInfo, "attachInfo");
    }

}

