// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetStoreAppListReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetStoreAppListReq";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetStoreAppListReq";
    }

    public int storeServiceType = 0;

    public String attachInfo = "";

    public int getStoreServiceType()
    {
        return storeServiceType;
    }

    public void  setStoreServiceType(int storeServiceType)
    {
        this.storeServiceType = storeServiceType;
    }

    public String getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public GetStoreAppListReq()
    {
        setStoreServiceType(storeServiceType);
        setAttachInfo(attachInfo);
    }

    public GetStoreAppListReq(int storeServiceType, String attachInfo)
    {
        setStoreServiceType(storeServiceType);
        setAttachInfo(attachInfo);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetStoreAppListReq t = (GetStoreAppListReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(storeServiceType, t.storeServiceType) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(storeServiceType, 0);
        if (null != attachInfo)
        {
            _os.write(attachInfo, 2);
        }
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setStoreServiceType((int) _is.read(storeServiceType, 0, false));

        setAttachInfo( _is.readString(2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(storeServiceType, "storeServiceType");
        _ds.display(attachInfo, "attachInfo");
    }

}

