// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetSearchSuggestionListRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetSearchSuggestionListRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetSearchSuggestionListRsp";
    }

    public java.util.Map<String, java.util.ArrayList<String>> suggestionList = null;

    public String attachInfo = "";

    public boolean hasMore = true;

    public java.util.Map<String, java.util.ArrayList<String>> getSuggestionList()
    {
        return suggestionList;
    }

    public void  setSuggestionList(java.util.Map<String, java.util.ArrayList<String>> suggestionList)
    {
        this.suggestionList = suggestionList;
    }

    public String getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public boolean getHasMore()
    {
        return hasMore;
    }

    public void  setHasMore(boolean hasMore)
    {
        this.hasMore = hasMore;
    }

    public GetSearchSuggestionListRsp()
    {
        setSuggestionList(suggestionList);
        setAttachInfo(attachInfo);
        setHasMore(hasMore);
    }

    public GetSearchSuggestionListRsp(java.util.Map<String, java.util.ArrayList<String>> suggestionList, String attachInfo, boolean hasMore)
    {
        setSuggestionList(suggestionList);
        setAttachInfo(attachInfo);
        setHasMore(hasMore);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetSearchSuggestionListRsp t = (GetSearchSuggestionListRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(suggestionList, t.suggestionList) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) && 
            com.duowan.taf.jce.JceUtil.equals(hasMore, t.hasMore) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != suggestionList)
        {
            _os.write(suggestionList, 0);
        }
        if (null != attachInfo)
        {
            _os.write(attachInfo, 1);
        }
        _os.write(hasMore, 2);
    }

    static java.util.Map<String, java.util.ArrayList<String>> cache_suggestionList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_suggestionList)
        {
            cache_suggestionList = new java.util.HashMap<String, java.util.ArrayList<String>>();
            String __var_22 = "";
            java.util.ArrayList<String> __var_23 = new java.util.ArrayList<String>();
            String __var_24 = "";
            ((java.util.ArrayList<String>)__var_23).add(__var_24);
            cache_suggestionList.put(__var_22, __var_23);
        }
        setSuggestionList((java.util.Map<String, java.util.ArrayList<String>>) _is.read(cache_suggestionList, 0, false));

        setAttachInfo( _is.readString(1, false));

        setHasMore((boolean) _is.read(hasMore, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(suggestionList, "suggestionList");
        _ds.display(attachInfo, "attachInfo");
        _ds.display(hasMore, "hasMore");
    }

}

