// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetStoreAppListRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetStoreAppListRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetStoreAppListRsp";
    }

    public java.util.ArrayList<com.duowan.gamenews.StoreAppInfo> appList = null;

    public int myTdou = 0;

    public String attachInfo = "";

    public boolean hasMore = true;

    public String alertMsg = "";

    public java.util.ArrayList<com.duowan.gamenews.StoreAppInfo> getAppList()
    {
        return appList;
    }

    public void  setAppList(java.util.ArrayList<com.duowan.gamenews.StoreAppInfo> appList)
    {
        this.appList = appList;
    }

    public int getMyTdou()
    {
        return myTdou;
    }

    public void  setMyTdou(int myTdou)
    {
        this.myTdou = myTdou;
    }

    public String getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public boolean getHasMore()
    {
        return hasMore;
    }

    public void  setHasMore(boolean hasMore)
    {
        this.hasMore = hasMore;
    }

    public String getAlertMsg()
    {
        return alertMsg;
    }

    public void  setAlertMsg(String alertMsg)
    {
        this.alertMsg = alertMsg;
    }

    public GetStoreAppListRsp()
    {
        setAppList(appList);
        setMyTdou(myTdou);
        setAttachInfo(attachInfo);
        setHasMore(hasMore);
        setAlertMsg(alertMsg);
    }

    public GetStoreAppListRsp(java.util.ArrayList<com.duowan.gamenews.StoreAppInfo> appList, int myTdou, String attachInfo, boolean hasMore, String alertMsg)
    {
        setAppList(appList);
        setMyTdou(myTdou);
        setAttachInfo(attachInfo);
        setHasMore(hasMore);
        setAlertMsg(alertMsg);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetStoreAppListRsp t = (GetStoreAppListRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(appList, t.appList) && 
            com.duowan.taf.jce.JceUtil.equals(myTdou, t.myTdou) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) && 
            com.duowan.taf.jce.JceUtil.equals(hasMore, t.hasMore) && 
            com.duowan.taf.jce.JceUtil.equals(alertMsg, t.alertMsg) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != appList)
        {
            _os.write(appList, 0);
        }
        _os.write(myTdou, 1);
        if (null != attachInfo)
        {
            _os.write(attachInfo, 2);
        }
        _os.write(hasMore, 3);
        if (null != alertMsg)
        {
            _os.write(alertMsg, 4);
        }
    }

    static java.util.ArrayList<com.duowan.gamenews.StoreAppInfo> cache_appList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_appList)
        {
            cache_appList = new java.util.ArrayList<com.duowan.gamenews.StoreAppInfo>();
            com.duowan.gamenews.StoreAppInfo __var_83 = new com.duowan.gamenews.StoreAppInfo();
            ((java.util.ArrayList<com.duowan.gamenews.StoreAppInfo>)cache_appList).add(__var_83);
        }
        setAppList((java.util.ArrayList<com.duowan.gamenews.StoreAppInfo>) _is.read(cache_appList, 0, false));

        setMyTdou((int) _is.read(myTdou, 1, false));

        setAttachInfo( _is.readString(2, false));

        setHasMore((boolean) _is.read(hasMore, 3, false));

        setAlertMsg( _is.readString(4, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(appList, "appList");
        _ds.display(myTdou, "myTdou");
        _ds.display(attachInfo, "attachInfo");
        _ds.display(hasMore, "hasMore");
        _ds.display(alertMsg, "alertMsg");
    }

}

