// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetTeamListRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetTeamListRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetTeamListRsp";
    }

    public java.util.ArrayList<com.duowan.gamenews.Team> teamList = null;

    public String attachInfo = "";

    public java.util.ArrayList<com.duowan.gamenews.Team> getTeamList()
    {
        return teamList;
    }

    public void  setTeamList(java.util.ArrayList<com.duowan.gamenews.Team> teamList)
    {
        this.teamList = teamList;
    }

    public String getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public GetTeamListRsp()
    {
        setTeamList(teamList);
        setAttachInfo(attachInfo);
    }

    public GetTeamListRsp(java.util.ArrayList<com.duowan.gamenews.Team> teamList, String attachInfo)
    {
        setTeamList(teamList);
        setAttachInfo(attachInfo);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetTeamListRsp t = (GetTeamListRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(teamList, t.teamList) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != teamList)
        {
            _os.write(teamList, 0);
        }
        if (null != attachInfo)
        {
            _os.write(attachInfo, 1);
        }
    }

    static java.util.ArrayList<com.duowan.gamenews.Team> cache_teamList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_teamList)
        {
            cache_teamList = new java.util.ArrayList<com.duowan.gamenews.Team>();
            com.duowan.gamenews.Team __var_66 = new com.duowan.gamenews.Team();
            ((java.util.ArrayList<com.duowan.gamenews.Team>)cache_teamList).add(__var_66);
        }
        setTeamList((java.util.ArrayList<com.duowan.gamenews.Team>) _is.read(cache_teamList, 0, false));

        setAttachInfo( _is.readString(1, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(teamList, "teamList");
        _ds.display(attachInfo, "attachInfo");
    }

}

