// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetUnionListRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetUnionListRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetUnionListRsp";
    }

    public java.util.ArrayList<com.duowan.gamenews.UnionInfo> unionList = null;

    public String attachInfo = "";

    public boolean hasMore = true;

    public java.util.ArrayList<com.duowan.gamenews.UnionInfo> getUnionList()
    {
        return unionList;
    }

    public void  setUnionList(java.util.ArrayList<com.duowan.gamenews.UnionInfo> unionList)
    {
        this.unionList = unionList;
    }

    public String getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public boolean getHasMore()
    {
        return hasMore;
    }

    public void  setHasMore(boolean hasMore)
    {
        this.hasMore = hasMore;
    }

    public GetUnionListRsp()
    {
        setUnionList(unionList);
        setAttachInfo(attachInfo);
        setHasMore(hasMore);
    }

    public GetUnionListRsp(java.util.ArrayList<com.duowan.gamenews.UnionInfo> unionList, String attachInfo, boolean hasMore)
    {
        setUnionList(unionList);
        setAttachInfo(attachInfo);
        setHasMore(hasMore);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetUnionListRsp t = (GetUnionListRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(unionList, t.unionList) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) && 
            com.duowan.taf.jce.JceUtil.equals(hasMore, t.hasMore) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != unionList)
        {
            _os.write(unionList, 0);
        }
        if (null != attachInfo)
        {
            _os.write(attachInfo, 1);
        }
        _os.write(hasMore, 2);
    }

    static java.util.ArrayList<com.duowan.gamenews.UnionInfo> cache_unionList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_unionList)
        {
            cache_unionList = new java.util.ArrayList<com.duowan.gamenews.UnionInfo>();
            com.duowan.gamenews.UnionInfo __var_66 = new com.duowan.gamenews.UnionInfo();
            ((java.util.ArrayList<com.duowan.gamenews.UnionInfo>)cache_unionList).add(__var_66);
        }
        setUnionList((java.util.ArrayList<com.duowan.gamenews.UnionInfo>) _is.read(cache_unionList, 0, false));

        setAttachInfo( _is.readString(1, false));

        setHasMore((boolean) _is.read(hasMore, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(unionList, "unionList");
        _ds.display(attachInfo, "attachInfo");
        _ds.display(hasMore, "hasMore");
    }

}

