// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetVideoUrlRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetVideoUrlRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetVideoUrlRsp";
    }

    public String url = "";

    public int videoFlag = 0;

    public String title = "";

    public String getUrl()
    {
        return url;
    }

    public void  setUrl(String url)
    {
        this.url = url;
    }

    public int getVideoFlag()
    {
        return videoFlag;
    }

    public void  setVideoFlag(int videoFlag)
    {
        this.videoFlag = videoFlag;
    }

    public String getTitle()
    {
        return title;
    }

    public void  setTitle(String title)
    {
        this.title = title;
    }

    public GetVideoUrlRsp()
    {
        setUrl(url);
        setVideoFlag(videoFlag);
        setTitle(title);
    }

    public GetVideoUrlRsp(String url, int videoFlag, String title)
    {
        setUrl(url);
        setVideoFlag(videoFlag);
        setTitle(title);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetVideoUrlRsp t = (GetVideoUrlRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(url, t.url) && 
            com.duowan.taf.jce.JceUtil.equals(videoFlag, t.videoFlag) && 
            com.duowan.taf.jce.JceUtil.equals(title, t.title) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != url)
        {
            _os.write(url, 0);
        }
        _os.write(videoFlag, 1);
        if (null != title)
        {
            _os.write(title, 2);
        }
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setUrl( _is.readString(0, false));

        setVideoFlag((int) _is.read(videoFlag, 1, false));

        setTitle( _is.readString(2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(url, "url");
        _ds.display(videoFlag, "videoFlag");
        _ds.display(title, "title");
    }

}

