// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class Like
{
    private static Like[] __values = new Like[3];
    private int __value;
    private String __T = new String();

    public static final int _HAS_NULL = 0;
    public static final Like HAS_NULL = new Like(0,_HAS_NULL,"HAS_NULL");
    public static final int _HAS_PRAISE = 1;
    public static final Like HAS_PRAISE = new Like(1,_HAS_PRAISE,"HAS_PRAISE");
    public static final int _HAS_STAMP = 2;
    public static final Like HAS_STAMP = new Like(2,_HAS_STAMP,"HAS_STAMP");

    public static Like convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static Like convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private Like(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
