// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class LikeReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.LikeReq";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.LikeReq";
    }

    public int likeType = 0;

    public long articleId = 0;

    public String commentId = "";

    public int getLikeType()
    {
        return likeType;
    }

    public void  setLikeType(int likeType)
    {
        this.likeType = likeType;
    }

    public long getArticleId()
    {
        return articleId;
    }

    public void  setArticleId(long articleId)
    {
        this.articleId = articleId;
    }

    public String getCommentId()
    {
        return commentId;
    }

    public void  setCommentId(String commentId)
    {
        this.commentId = commentId;
    }

    public LikeReq()
    {
        setLikeType(likeType);
        setArticleId(articleId);
        setCommentId(commentId);
    }

    public LikeReq(int likeType, long articleId, String commentId)
    {
        setLikeType(likeType);
        setArticleId(articleId);
        setCommentId(commentId);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        LikeReq t = (LikeReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(likeType, t.likeType) && 
            com.duowan.taf.jce.JceUtil.equals(articleId, t.articleId) && 
            com.duowan.taf.jce.JceUtil.equals(commentId, t.commentId) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(likeType, 0);
        _os.write(articleId, 1);
        if (null != commentId)
        {
            _os.write(commentId, 2);
        }
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setLikeType((int) _is.read(likeType, 0, false));

        setArticleId((long) _is.read(articleId, 1, false));

        setCommentId( _is.readString(2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(likeType, "likeType");
        _ds.display(articleId, "articleId");
        _ds.display(commentId, "commentId");
    }

}

