// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class LikeType
{
    private static LikeType[] __values = new LikeType[2];
    private int __value;
    private String __T = new String();

    public static final int _LIKE_TYPE_LIKE = 1;
    public static final LikeType LIKE_TYPE_LIKE = new LikeType(0,_LIKE_TYPE_LIKE,"LIKE_TYPE_LIKE");
    public static final int _LIKE_TYPE_DISLIKE = 2;
    public static final LikeType LIKE_TYPE_DISLIKE = new LikeType(1,_LIKE_TYPE_DISLIKE,"LIKE_TYPE_DISLIKE");

    public static LikeType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static LikeType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private LikeType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
