// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class LoginActionFlag
{
    private static LoginActionFlag[] __values = new LoginActionFlag[2];
    private int __value;
    private String __T = new String();

    public static final int _LOGIN_ACTION_FLAG_YY_TDOU = 1;
    public static final LoginActionFlag LOGIN_ACTION_FLAG_YY_TDOU = new LoginActionFlag(0,_LOGIN_ACTION_FLAG_YY_TDOU,"LOGIN_ACTION_FLAG_YY_TDOU");
    public static final int _LOGIN_ACTION_FLAG_YY_TOKEN = 2;
    public static final LoginActionFlag LOGIN_ACTION_FLAG_YY_TOKEN = new LoginActionFlag(1,_LOGIN_ACTION_FLAG_YY_TOKEN,"LOGIN_ACTION_FLAG_YY_TOKEN");

    public static LoginActionFlag convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static LoginActionFlag convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private LoginActionFlag(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
