// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class PlatType
{
    private static PlatType[] __values = new PlatType[4];
    private int __value;
    private String __T = new String();

    public static final int _PLAT_TYPE_DEFAULT = 0;
    public static final PlatType PLAT_TYPE_DEFAULT = new PlatType(0,_PLAT_TYPE_DEFAULT,"PLAT_TYPE_DEFAULT");
    public static final int _PLAT_TYPE_QQ = 1;
    public static final PlatType PLAT_TYPE_QQ = new PlatType(1,_PLAT_TYPE_QQ,"PLAT_TYPE_QQ");
    public static final int _PLAT_TYPE_SINA = 2;
    public static final PlatType PLAT_TYPE_SINA = new PlatType(2,_PLAT_TYPE_SINA,"PLAT_TYPE_SINA");
    public static final int _PLAT_TYPE_YY = 3;
    public static final PlatType PLAT_TYPE_YY = new PlatType(3,_PLAT_TYPE_YY,"PLAT_TYPE_YY");

    public static PlatType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static PlatType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private PlatType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
