// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class PushInitReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.PushInitReq";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.PushInitReq";
    }

    public String userId = "";

    public String getUserId()
    {
        return userId;
    }

    public void  setUserId(String userId)
    {
        this.userId = userId;
    }

    public PushInitReq()
    {
        setUserId(userId);
    }

    public PushInitReq(String userId)
    {
        setUserId(userId);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        PushInitReq t = (PushInitReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(userId, t.userId) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != userId)
        {
            _os.write(userId, 0);
        }
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setUserId( _is.readString(0, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(userId, "userId");
    }

}

