// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class RaceFlag
{
    private static RaceFlag[] __values = new RaceFlag[1];
    private int __value;
    private String __T = new String();

    public static final int _RACE_JUE_FLAG = 1;
    public static final RaceFlag RACE_JUE_FLAG = new RaceFlag(0,_RACE_JUE_FLAG,"RACE_JUE_FLAG");

    public static RaceFlag convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static RaceFlag convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private RaceFlag(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
