// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class RaceTopicType
{
    private static RaceTopicType[] __values = new RaceTopicType[2];
    private int __value;
    private String __T = new String();

    public static final int _RACE_TYPE_UNION = 1;
    public static final RaceTopicType RACE_TYPE_UNION = new RaceTopicType(0,_RACE_TYPE_UNION,"RACE_TYPE_UNION");
    public static final int _RACE_TYPE_PERSON = 2;
    public static final RaceTopicType RACE_TYPE_PERSON = new RaceTopicType(1,_RACE_TYPE_PERSON,"RACE_TYPE_PERSON");

    public static RaceTopicType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static RaceTopicType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private RaceTopicType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
