// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class RaceTopicInfo extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.RaceTopicInfo";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.RaceTopicInfo";
    }

    public long id = 0;

    public String img = "";

    public String name = "";

    public int raceTopicType = 0;

    public int raceTopicFlag = 0;

    public java.util.Map<Integer, String> extraInfo = null;

    public long getId()
    {
        return id;
    }

    public void  setId(long id)
    {
        this.id = id;
    }

    public String getImg()
    {
        return img;
    }

    public void  setImg(String img)
    {
        this.img = img;
    }

    public String getName()
    {
        return name;
    }

    public void  setName(String name)
    {
        this.name = name;
    }

    public int getRaceTopicType()
    {
        return raceTopicType;
    }

    public void  setRaceTopicType(int raceTopicType)
    {
        this.raceTopicType = raceTopicType;
    }

    public int getRaceTopicFlag()
    {
        return raceTopicFlag;
    }

    public void  setRaceTopicFlag(int raceTopicFlag)
    {
        this.raceTopicFlag = raceTopicFlag;
    }

    public java.util.Map<Integer, String> getExtraInfo()
    {
        return extraInfo;
    }

    public void  setExtraInfo(java.util.Map<Integer, String> extraInfo)
    {
        this.extraInfo = extraInfo;
    }

    public RaceTopicInfo()
    {
        setId(id);
        setImg(img);
        setName(name);
        setRaceTopicType(raceTopicType);
        setRaceTopicFlag(raceTopicFlag);
        setExtraInfo(extraInfo);
    }

    public RaceTopicInfo(long id, String img, String name, int raceTopicType, int raceTopicFlag, java.util.Map<Integer, String> extraInfo)
    {
        setId(id);
        setImg(img);
        setName(name);
        setRaceTopicType(raceTopicType);
        setRaceTopicFlag(raceTopicFlag);
        setExtraInfo(extraInfo);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        RaceTopicInfo t = (RaceTopicInfo) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(id, t.id) && 
            com.duowan.taf.jce.JceUtil.equals(img, t.img) && 
            com.duowan.taf.jce.JceUtil.equals(name, t.name) && 
            com.duowan.taf.jce.JceUtil.equals(raceTopicType, t.raceTopicType) && 
            com.duowan.taf.jce.JceUtil.equals(raceTopicFlag, t.raceTopicFlag) && 
            com.duowan.taf.jce.JceUtil.equals(extraInfo, t.extraInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(id, 0);
        if (null != img)
        {
            _os.write(img, 1);
        }
        if (null != name)
        {
            _os.write(name, 2);
        }
        _os.write(raceTopicType, 3);
        _os.write(raceTopicFlag, 4);
        if (null != extraInfo)
        {
            _os.write(extraInfo, 5);
        }
    }

    static java.util.Map<Integer, String> cache_extraInfo;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setId((long) _is.read(id, 0, false));

        setImg( _is.readString(1, false));

        setName( _is.readString(2, false));

        setRaceTopicType((int) _is.read(raceTopicType, 3, false));

        setRaceTopicFlag((int) _is.read(raceTopicFlag, 4, false));

        if(null == cache_extraInfo)
        {
            cache_extraInfo = new java.util.HashMap<Integer, String>();
            Integer __var_67 = 0;
            String __var_68 = "";
            cache_extraInfo.put(__var_67, __var_68);
        }
        setExtraInfo((java.util.Map<Integer, String>) _is.read(cache_extraInfo, 5, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(id, "id");
        _ds.display(img, "img");
        _ds.display(name, "name");
        _ds.display(raceTopicType, "raceTopicType");
        _ds.display(raceTopicFlag, "raceTopicFlag");
        _ds.display(extraInfo, "extraInfo");
    }

}

