// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class RefreshType
{
    private static RefreshType[] __values = new RefreshType[2];
    private int __value;
    private String __T = new String();

    public static final int _REFRESH_TYPE_REFRESH = 1;
    public static final RefreshType REFRESH_TYPE_REFRESH = new RefreshType(0,_REFRESH_TYPE_REFRESH,"REFRESH_TYPE_REFRESH");
    public static final int _REFRESH_TYPE_LOAD_MORE = 2;
    public static final RefreshType REFRESH_TYPE_LOAD_MORE = new RefreshType(1,_REFRESH_TYPE_LOAD_MORE,"REFRESH_TYPE_LOAD_MORE");

    public static RefreshType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static RefreshType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private RefreshType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
