// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class SearchChannelReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.SearchChannelReq";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.SearchChannelReq";
    }

    public String keyword = "";

    public String attachInfo = "";

    public int count = 0;

    public String getKeyword()
    {
        return keyword;
    }

    public void  setKeyword(String keyword)
    {
        this.keyword = keyword;
    }

    public String getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(String attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public int getCount()
    {
        return count;
    }

    public void  setCount(int count)
    {
        this.count = count;
    }

    public SearchChannelReq()
    {
        setKeyword(keyword);
        setAttachInfo(attachInfo);
        setCount(count);
    }

    public SearchChannelReq(String keyword, String attachInfo, int count)
    {
        setKeyword(keyword);
        setAttachInfo(attachInfo);
        setCount(count);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        SearchChannelReq t = (SearchChannelReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(keyword, t.keyword) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) && 
            com.duowan.taf.jce.JceUtil.equals(count, t.count) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != keyword)
        {
            _os.write(keyword, 0);
        }
        if (null != attachInfo)
        {
            _os.write(attachInfo, 1);
        }
        _os.write(count, 2);
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setKeyword( _is.readString(0, false));

        setAttachInfo( _is.readString(1, false));

        setCount((int) _is.read(count, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(keyword, "keyword");
        _ds.display(attachInfo, "attachInfo");
        _ds.display(count, "count");
    }

}

