// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class swiths
{
    private static swiths[] __values = new swiths[6];
    private int __value;
    private String __T = new String();

    public static final int _ENUM_SWITCHS_SIGN = 1;
    public static final swiths ENUM_SWITCHS_SIGN = new swiths(0,_ENUM_SWITCHS_SIGN,"ENUM_SWITCHS_SIGN");
    public static final int _ENUM_SWITCHS_ACTIVITY = 2;
    public static final swiths ENUM_SWITCHS_ACTIVITY = new swiths(1,_ENUM_SWITCHS_ACTIVITY,"ENUM_SWITCHS_ACTIVITY");
    public static final int _ENUM_SWITCHS_GIFT = 3;
    public static final swiths ENUM_SWITCHS_GIFT = new swiths(2,_ENUM_SWITCHS_GIFT,"ENUM_SWITCHS_GIFT");
    public static final int _ENUM_SWITCHS_LOGIN = 4;
    public static final swiths ENUM_SWITCHS_LOGIN = new swiths(3,_ENUM_SWITCHS_LOGIN,"ENUM_SWITCHS_LOGIN");
    public static final int _ENUM_SWITCHS_RIGHT_TOP = 5;
    public static final swiths ENUM_SWITCHS_RIGHT_TOP = new swiths(4,_ENUM_SWITCHS_RIGHT_TOP,"ENUM_SWITCHS_RIGHT_TOP");
    public static final int _ENUM_SWITCHS_REGISTER = 6;
    public static final swiths ENUM_SWITCHS_REGISTER = new swiths(5,_ENUM_SWITCHS_REGISTER,"ENUM_SWITCHS_REGISTER");

    public static swiths convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static swiths convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private swiths(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
