// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class TeamFlag
{
    private static TeamFlag[] __values = new TeamFlag[1];
    private int __value;
    private String __T = new String();

    public static final int _TEAM_FLAG_HOT = 1;
    public static final TeamFlag TEAM_FLAG_HOT = new TeamFlag(0,_TEAM_FLAG_HOT,"TEAM_FLAG_HOT");

    public static TeamFlag convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static TeamFlag convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private TeamFlag(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
