// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class Team extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.Team";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.Team";
    }

    public String name = "";

    public String icon = "";

    public boolean isGuest = true;

    public String id = "";

    public String leagueId = "";

    public String leagueName = "";

    public String sportTypeId = "";

    public String sportTypeName = "";

    public int flag = 0;

    public String getName()
    {
        return name;
    }

    public void  setName(String name)
    {
        this.name = name;
    }

    public String getIcon()
    {
        return icon;
    }

    public void  setIcon(String icon)
    {
        this.icon = icon;
    }

    public boolean getIsGuest()
    {
        return isGuest;
    }

    public void  setIsGuest(boolean isGuest)
    {
        this.isGuest = isGuest;
    }

    public String getId()
    {
        return id;
    }

    public void  setId(String id)
    {
        this.id = id;
    }

    public String getLeagueId()
    {
        return leagueId;
    }

    public void  setLeagueId(String leagueId)
    {
        this.leagueId = leagueId;
    }

    public String getLeagueName()
    {
        return leagueName;
    }

    public void  setLeagueName(String leagueName)
    {
        this.leagueName = leagueName;
    }

    public String getSportTypeId()
    {
        return sportTypeId;
    }

    public void  setSportTypeId(String sportTypeId)
    {
        this.sportTypeId = sportTypeId;
    }

    public String getSportTypeName()
    {
        return sportTypeName;
    }

    public void  setSportTypeName(String sportTypeName)
    {
        this.sportTypeName = sportTypeName;
    }

    public int getFlag()
    {
        return flag;
    }

    public void  setFlag(int flag)
    {
        this.flag = flag;
    }

    public Team()
    {
        setName(name);
        setIcon(icon);
        setIsGuest(isGuest);
        setId(id);
        setLeagueId(leagueId);
        setLeagueName(leagueName);
        setSportTypeId(sportTypeId);
        setSportTypeName(sportTypeName);
        setFlag(flag);
    }

    public Team(String name, String icon, boolean isGuest, String id, String leagueId, String leagueName, String sportTypeId, String sportTypeName, int flag)
    {
        setName(name);
        setIcon(icon);
        setIsGuest(isGuest);
        setId(id);
        setLeagueId(leagueId);
        setLeagueName(leagueName);
        setSportTypeId(sportTypeId);
        setSportTypeName(sportTypeName);
        setFlag(flag);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        Team t = (Team) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(name, t.name) && 
            com.duowan.taf.jce.JceUtil.equals(icon, t.icon) && 
            com.duowan.taf.jce.JceUtil.equals(isGuest, t.isGuest) && 
            com.duowan.taf.jce.JceUtil.equals(id, t.id) && 
            com.duowan.taf.jce.JceUtil.equals(leagueId, t.leagueId) && 
            com.duowan.taf.jce.JceUtil.equals(leagueName, t.leagueName) && 
            com.duowan.taf.jce.JceUtil.equals(sportTypeId, t.sportTypeId) && 
            com.duowan.taf.jce.JceUtil.equals(sportTypeName, t.sportTypeName) && 
            com.duowan.taf.jce.JceUtil.equals(flag, t.flag) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != name)
        {
            _os.write(name, 0);
        }
        if (null != icon)
        {
            _os.write(icon, 1);
        }
        _os.write(isGuest, 2);
        if (null != id)
        {
            _os.write(id, 3);
        }
        if (null != leagueId)
        {
            _os.write(leagueId, 4);
        }
        if (null != leagueName)
        {
            _os.write(leagueName, 5);
        }
        if (null != sportTypeId)
        {
            _os.write(sportTypeId, 6);
        }
        if (null != sportTypeName)
        {
            _os.write(sportTypeName, 7);
        }
        _os.write(flag, 8);
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setName( _is.readString(0, false));

        setIcon( _is.readString(1, false));

        setIsGuest((boolean) _is.read(isGuest, 2, false));

        setId( _is.readString(3, false));

        setLeagueId( _is.readString(4, false));

        setLeagueName( _is.readString(5, false));

        setSportTypeId( _is.readString(6, false));

        setSportTypeName( _is.readString(7, false));

        setFlag((int) _is.read(flag, 8, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(name, "name");
        _ds.display(icon, "icon");
        _ds.display(isGuest, "isGuest");
        _ds.display(id, "id");
        _ds.display(leagueId, "leagueId");
        _ds.display(leagueName, "leagueName");
        _ds.display(sportTypeId, "sportTypeId");
        _ds.display(sportTypeName, "sportTypeName");
        _ds.display(flag, "flag");
    }

}

