// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class UnionType
{
    private static UnionType[] __values = new UnionType[2];
    private int __value;
    private String __T = new String();

    public static final int _UNION_TYPE_TOP = 1;
    public static final UnionType UNION_TYPE_TOP = new UnionType(0,_UNION_TYPE_TOP,"UNION_TYPE_TOP");
    public static final int _UNION_TYPE_OTHER = 2;
    public static final UnionType UNION_TYPE_OTHER = new UnionType(1,_UNION_TYPE_OTHER,"UNION_TYPE_OTHER");

    public static UnionType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static UnionType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private UnionType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
