// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class UnionInfo extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.UnionInfo";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.UnionInfo";
    }

    public long id = 0;

    public String name = "";

    public String img = "";

    public long heat = 0;

    public String desc = "";

    public long getId()
    {
        return id;
    }

    public void  setId(long id)
    {
        this.id = id;
    }

    public String getName()
    {
        return name;
    }

    public void  setName(String name)
    {
        this.name = name;
    }

    public String getImg()
    {
        return img;
    }

    public void  setImg(String img)
    {
        this.img = img;
    }

    public long getHeat()
    {
        return heat;
    }

    public void  setHeat(long heat)
    {
        this.heat = heat;
    }

    public String getDesc()
    {
        return desc;
    }

    public void  setDesc(String desc)
    {
        this.desc = desc;
    }

    public UnionInfo()
    {
        setId(id);
        setName(name);
        setImg(img);
        setHeat(heat);
        setDesc(desc);
    }

    public UnionInfo(long id, String name, String img, long heat, String desc)
    {
        setId(id);
        setName(name);
        setImg(img);
        setHeat(heat);
        setDesc(desc);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        UnionInfo t = (UnionInfo) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(id, t.id) && 
            com.duowan.taf.jce.JceUtil.equals(name, t.name) && 
            com.duowan.taf.jce.JceUtil.equals(img, t.img) && 
            com.duowan.taf.jce.JceUtil.equals(heat, t.heat) && 
            com.duowan.taf.jce.JceUtil.equals(desc, t.desc) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(id, 0);
        if (null != name)
        {
            _os.write(name, 1);
        }
        if (null != img)
        {
            _os.write(img, 2);
        }
        _os.write(heat, 3);
        if (null != desc)
        {
            _os.write(desc, 4);
        }
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setId((long) _is.read(id, 0, false));

        setName( _is.readString(1, false));

        setImg( _is.readString(2, false));

        setHeat((long) _is.read(heat, 3, false));

        setDesc( _is.readString(4, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(id, "id");
        _ds.display(name, "name");
        _ds.display(img, "img");
        _ds.display(heat, "heat");
        _ds.display(desc, "desc");
    }

}

