// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class UpdateMyFavChannelListReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.UpdateMyFavChannelListReq";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.UpdateMyFavChannelListReq";
    }

    public java.util.ArrayList<Integer> channelList = null;

    public java.util.ArrayList<Integer> getChannelList()
    {
        return channelList;
    }

    public void  setChannelList(java.util.ArrayList<Integer> channelList)
    {
        this.channelList = channelList;
    }

    public UpdateMyFavChannelListReq()
    {
        setChannelList(channelList);
    }

    public UpdateMyFavChannelListReq(java.util.ArrayList<Integer> channelList)
    {
        setChannelList(channelList);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        UpdateMyFavChannelListReq t = (UpdateMyFavChannelListReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(channelList, t.channelList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != channelList)
        {
            _os.write(channelList, 0);
        }
    }

    static java.util.ArrayList<Integer> cache_channelList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_channelList)
        {
            cache_channelList = new java.util.ArrayList<Integer>();
            Integer __var_27 = 0;
            ((java.util.ArrayList<Integer>)cache_channelList).add(__var_27);
        }
        setChannelList((java.util.ArrayList<Integer>) _is.read(cache_channelList, 0, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(channelList, "channelList");
    }

}

