// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class User extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.User";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.User";
    }

    public String id = "";

    public String name = "";

    public String icon = "";

    public String getId()
    {
        return id;
    }

    public void  setId(String id)
    {
        this.id = id;
    }

    public String getName()
    {
        return name;
    }

    public void  setName(String name)
    {
        this.name = name;
    }

    public String getIcon()
    {
        return icon;
    }

    public void  setIcon(String icon)
    {
        this.icon = icon;
    }

    public User()
    {
        setId(id);
        setName(name);
        setIcon(icon);
    }

    public User(String id, String name, String icon)
    {
        setId(id);
        setName(name);
        setIcon(icon);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        User t = (User) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(id, t.id) && 
            com.duowan.taf.jce.JceUtil.equals(name, t.name) && 
            com.duowan.taf.jce.JceUtil.equals(icon, t.icon) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != id)
        {
            _os.write(id, 1);
        }
        if (null != name)
        {
            _os.write(name, 2);
        }
        if (null != icon)
        {
            _os.write(icon, 3);
        }
    }


    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setId( _is.readString(1, false));

        setName( _is.readString(2, false));

        setIcon( _is.readString(3, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(id, "id");
        _ds.display(name, "name");
        _ds.display(icon, "icon");
    }

}

