// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class UserInitReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.UserInitReq";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.UserInitReq";
    }

    public int deviceType = 0;

    public String uuid = "";

    public java.util.Map<Integer, String> socialAccessToken = null;

    public String userName = "";

    public String userIcon = "";

    public int platType = 0;

    public String appPlat = "";

    public int getDeviceType()
    {
        return deviceType;
    }

    public void  setDeviceType(int deviceType)
    {
        this.deviceType = deviceType;
    }

    public String getUuid()
    {
        return uuid;
    }

    public void  setUuid(String uuid)
    {
        this.uuid = uuid;
    }

    public java.util.Map<Integer, String> getSocialAccessToken()
    {
        return socialAccessToken;
    }

    public void  setSocialAccessToken(java.util.Map<Integer, String> socialAccessToken)
    {
        this.socialAccessToken = socialAccessToken;
    }

    public String getUserName()
    {
        return userName;
    }

    public void  setUserName(String userName)
    {
        this.userName = userName;
    }

    public String getUserIcon()
    {
        return userIcon;
    }

    public void  setUserIcon(String userIcon)
    {
        this.userIcon = userIcon;
    }

    public int getPlatType()
    {
        return platType;
    }

    public void  setPlatType(int platType)
    {
        this.platType = platType;
    }

    public String getAppPlat()
    {
        return appPlat;
    }

    public void  setAppPlat(String appPlat)
    {
        this.appPlat = appPlat;
    }

    public UserInitReq()
    {
        setDeviceType(deviceType);
        setUuid(uuid);
        setSocialAccessToken(socialAccessToken);
        setUserName(userName);
        setUserIcon(userIcon);
        setPlatType(platType);
        setAppPlat(appPlat);
    }

    public UserInitReq(int deviceType, String uuid, java.util.Map<Integer, String> socialAccessToken, String userName, String userIcon, int platType, String appPlat)
    {
        setDeviceType(deviceType);
        setUuid(uuid);
        setSocialAccessToken(socialAccessToken);
        setUserName(userName);
        setUserIcon(userIcon);
        setPlatType(platType);
        setAppPlat(appPlat);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        UserInitReq t = (UserInitReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(deviceType, t.deviceType) && 
            com.duowan.taf.jce.JceUtil.equals(uuid, t.uuid) && 
            com.duowan.taf.jce.JceUtil.equals(socialAccessToken, t.socialAccessToken) && 
            com.duowan.taf.jce.JceUtil.equals(userName, t.userName) && 
            com.duowan.taf.jce.JceUtil.equals(userIcon, t.userIcon) && 
            com.duowan.taf.jce.JceUtil.equals(platType, t.platType) && 
            com.duowan.taf.jce.JceUtil.equals(appPlat, t.appPlat) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        _os.write(deviceType, 0);
        if (null != uuid)
        {
            _os.write(uuid, 1);
        }
        if (null != socialAccessToken)
        {
            _os.write(socialAccessToken, 2);
        }
        if (null != userName)
        {
            _os.write(userName, 3);
        }
        if (null != userIcon)
        {
            _os.write(userIcon, 4);
        }
        _os.write(platType, 5);
        if (null != appPlat)
        {
            _os.write(appPlat, 6);
        }
    }

    static java.util.Map<Integer, String> cache_socialAccessToken;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setDeviceType((int) _is.read(deviceType, 0, false));

        setUuid( _is.readString(1, false));

        if(null == cache_socialAccessToken)
        {
            cache_socialAccessToken = new java.util.HashMap<Integer, String>();
            Integer __var_14 = 0;
            String __var_15 = "";
            cache_socialAccessToken.put(__var_14, __var_15);
        }
        setSocialAccessToken((java.util.Map<Integer, String>) _is.read(cache_socialAccessToken, 2, false));

        setUserName( _is.readString(3, false));

        setUserIcon( _is.readString(4, false));

        setPlatType((int) _is.read(platType, 5, false));

        setAppPlat( _is.readString(6, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(deviceType, "deviceType");
        _ds.display(uuid, "uuid");
        _ds.display(socialAccessToken, "socialAccessToken");
        _ds.display(userName, "userName");
        _ds.display(userIcon, "userIcon");
        _ds.display(platType, "platType");
        _ds.display(appPlat, "appPlat");
    }

}

