// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class UserInitRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.UserInitRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.UserInitRsp";
    }

    public String accessToken = "";

    public com.duowan.gamenews.User user = null;

    public int flag = 0;

    public java.util.Map<Integer, String> extraInfo = null;

    public String getAccessToken()
    {
        return accessToken;
    }

    public void  setAccessToken(String accessToken)
    {
        this.accessToken = accessToken;
    }

    public com.duowan.gamenews.User getUser()
    {
        return user;
    }

    public void  setUser(com.duowan.gamenews.User user)
    {
        this.user = user;
    }

    public int getFlag()
    {
        return flag;
    }

    public void  setFlag(int flag)
    {
        this.flag = flag;
    }

    public java.util.Map<Integer, String> getExtraInfo()
    {
        return extraInfo;
    }

    public void  setExtraInfo(java.util.Map<Integer, String> extraInfo)
    {
        this.extraInfo = extraInfo;
    }

    public UserInitRsp()
    {
        setAccessToken(accessToken);
        setUser(user);
        setFlag(flag);
        setExtraInfo(extraInfo);
    }

    public UserInitRsp(String accessToken, com.duowan.gamenews.User user, int flag, java.util.Map<Integer, String> extraInfo)
    {
        setAccessToken(accessToken);
        setUser(user);
        setFlag(flag);
        setExtraInfo(extraInfo);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        UserInitRsp t = (UserInitRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(accessToken, t.accessToken) && 
            com.duowan.taf.jce.JceUtil.equals(user, t.user) && 
            com.duowan.taf.jce.JceUtil.equals(flag, t.flag) && 
            com.duowan.taf.jce.JceUtil.equals(extraInfo, t.extraInfo) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != accessToken)
        {
            _os.write(accessToken, 0);
        }
        if (null != user)
        {
            _os.write(user, 1);
        }
        _os.write(flag, 2);
        if (null != extraInfo)
        {
            _os.write(extraInfo, 3);
        }
    }

    static com.duowan.gamenews.User cache_user;
    static java.util.Map<Integer, String> cache_extraInfo;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        setAccessToken( _is.readString(0, false));

        if(null == cache_user)
        {
            cache_user = new com.duowan.gamenews.User();
        }
        setUser((com.duowan.gamenews.User) _is.read(cache_user, 1, false));

        setFlag((int) _is.read(flag, 2, false));

        if(null == cache_extraInfo)
        {
            cache_extraInfo = new java.util.HashMap<Integer, String>();
            Integer __var_16 = 0;
            String __var_17 = "";
            cache_extraInfo.put(__var_16, __var_17);
        }
        setExtraInfo((java.util.Map<Integer, String>) _is.read(cache_extraInfo, 3, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(accessToken, "accessToken");
        _ds.display(user, "user");
        _ds.display(flag, "flag");
        _ds.display(extraInfo, "extraInfo");
    }

}

