// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.5
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class VideoFlag
{
    private static VideoFlag[] __values = new VideoFlag[2];
    private int __value;
    private String __T = new String();

    public static final int _VIDEO_FLAG_REDIRECT = 1;
    public static final VideoFlag VIDEO_FLAG_REDIRECT = new VideoFlag(0,_VIDEO_FLAG_REDIRECT,"VIDEO_FLAG_REDIRECT");
    public static final int _VIDEO_FLAG_SOURCE = 2;
    public static final VideoFlag VIDEO_FLAG_SOURCE = new VideoFlag(1,_VIDEO_FLAG_SOURCE,"VIDEO_FLAG_SOURCE");

    public static VideoFlag convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static VideoFlag convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private VideoFlag(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
